//! Exhaustive single-bit-flip sweep on a valid signature.
//!
//! Every one of the `8 * SIGNATURE_BYTES = 1184` single-bit
//! perturbations of a canonical KAT signature must be rejected (at
//! parse or at verify time) and must never panic, with the documented
//! exception of [`KAT_INHERENT_MALLEABLE_BITS`] (see below). A bit
//! position outside that allowlist that still verifies is signature
//! malleability the spec doesn't permit — the bit didn't contribute
//! to integrity, so an attacker who intercepts a message could rewrite
//! that bit and the recipient wouldn't notice.
//!
//! Sister test to [`malleability`](../malleability/index.html) — that
//! one mutates *typed components* (swap `n_bt` / `r_rsp`, replace
//! `curve_aux`, etc.), this one is the blind exhaustive sweep.
//!
//! Two granularities ship in this file:
//!
//! - [`bit_flip_sweep_kat0_rejects_all_perturbations`] runs only on KAT 0 and
//!   stays in the default `cargo test` / nextest suite (~3 min). It guards the
//!   minimal residual set.
//! - [`bit_flip_sweep_all_kats_matches_residuals`] is `#[ignore]` and sweeps
//!   every one of the 100 NIST-I KAT signatures (~25 min), asserting each
//!   signature's residual matches the pinned table below. Run via the `kat`
//!   nextest profile or `cargo test bit_flip_sweep_all_kats -- --ignored
//!   --nocapture`.
//!
//! # Inherent malleability
//!
//! Verify's `M_chl` application multiplies the scaled `E_chl`-basis by
//! a 4-entry scalar matrix and pushes the result through a chain of
//! 2-isogenies (the small even-response chain plus the outer (2,2)-
//! chain). Each isogeny step has a kernel of order 2 generated by
//! some 2-torsion point on its domain curve. Flipping the high bits of
//! an `M_chl` scalar shifts the corresponding output basis point by a
//! multiple of that 2-torsion generator — which the chain absorbs,
//! leaving the codomain curve and final hash unchanged.
//!
//! The residual size therefore grows roughly with `r_rsp` (more chain
//! steps absorb more bits), and the bit positions are always near the
//! top of one of the four `M_chl` entries (bits 528..1040 of the sig,
//! grouped into 4 × 128-bit scalars, top bit at position
//! `127 − n_bt` of each entry). Per-signature structural alignment
//! makes the exact count vary inside a class: e.g., `(n_bt = 0,
//! r_rsp = 1)` KATs land anywhere from 6 to 9 bits.
//!
//! These are not spec violations: the spec's `M_chl` entry bound
//! ([§4.5][§4.5] Alg. 4.9 step 5, enforced at parse by
//! `ChallengeMatrix::parse`) is `2^(e_rsp − n_bt + 2)` — the full
//! encoding range. The malleability is intrinsic to the matrix-then-
//! isogeny structure; tightening the byte encoding to remove it would
//! go beyond the spec. SQIsign as specified satisfies EUF-CMA but not
//! SUF-CMA.
//!
//! The residual table is pinned so a future change that adds or
//! removes a malleable bit fails loudly — either direction is
//! noteworthy.
//!
//! [§4.5]: https://sqisign.org/spec/sqisign-20250707.pdf#section.4.5

use sqisign_selkie::{
    SIGNATURE_BYTES, Signature, VERIFYING_KEY_BYTES, VerifyingKey, keys::kat_data::KAT_VECTORS,
};

/// Sig bit positions for which a single-bit flip leaves verify
/// accepting, per KAT. Indexed by KAT index in [`KAT_VECTORS`].
///
/// Generated by running the all-KATs sweep and recording each KAT's
/// empirical residual. See the module-level docs for the math.
const KAT_INHERENT_MALLEABLE_BITS: [&[usize]; 100] = [
    // KAT   0
    &[654, 655, 783, 910, 911, 1039],
    // KAT   1
    &[653, 654, 782, 909, 910, 1038],
    // KAT   2
    &[654, 655, 783, 910, 911, 1039],
    // KAT   3
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT   4
    &[652, 653, 654, 655, 781, 782, 783, 910, 911, 1039],
    // KAT   5
    &[652, 653, 654, 655, 781, 782, 783, 910, 911, 1038, 1039],
    // KAT   6
    &[652, 653, 654, 655, 781, 782, 783, 910, 911, 1039],
    // KAT   7
    &[654, 655, 783, 910, 911, 1039],
    // KAT   8
    &[653, 654, 782, 909, 910, 1037, 1038],
    // KAT   9
    &[652, 653, 781, 908, 909, 1037],
    // KAT  10
    &[654, 655, 783, 910, 911, 1039],
    // KAT  11
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  12
    &[654, 655, 783, 910, 911, 1039],
    // KAT  13
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  14
    &[653, 654, 781, 782, 909, 910, 1037, 1038],
    // KAT  15
    &[653, 654, 655, 781, 782, 783, 910, 911, 1038, 1039],
    // KAT  16
    &[653, 654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  17
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  18
    &[653, 654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  19
    &[653, 654, 782, 909, 910, 1037, 1038],
    // KAT  20
    &[654, 655, 783, 910, 911, 1039],
    // KAT  21
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  22
    &[653, 654, 782, 909, 910, 1038],
    // KAT  23
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  24
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  25
    &[654, 655, 783, 910, 911, 1039],
    // KAT  26
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  27
    &[654, 655, 783, 910, 911, 1039],
    // KAT  28
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  29
    &[653, 654, 782, 909, 910, 1038],
    // KAT  30
    &[
        651, 652, 653, 654, 655, 779, 780, 781, 782, 783, 910, 911, 1039,
    ],
    // KAT  31
    &[652, 653, 654, 655, 780, 781, 782, 783, 910, 911, 1039],
    // KAT  32
    &[652, 653, 654, 655, 780, 781, 782, 783, 910, 911, 1039],
    // KAT  33
    &[653, 654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  34
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  35
    &[654, 655, 783, 910, 911, 1039],
    // KAT  36
    &[654, 655, 783, 910, 911, 1039],
    // KAT  37
    &[654, 655, 783, 910, 911, 1039],
    // KAT  38
    &[654, 655, 783, 910, 911, 1039],
    // KAT  39
    &[654, 655, 783, 910, 911, 1039],
    // KAT  40
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  41
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  42
    &[654, 655, 783, 910, 911, 1039],
    // KAT  43
    &[653, 654, 782, 909, 910, 1038],
    // KAT  44
    &[654, 655, 783, 910, 911, 1039],
    // KAT  45
    &[654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  46
    &[654, 655, 783, 910, 911, 1039],
    // KAT  47
    &[654, 655, 783, 910, 911, 1039],
    // KAT  48
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  49
    &[654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  50
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  51
    &[654, 655, 783, 910, 911, 1039],
    // KAT  52
    &[653, 654, 781, 782, 909, 910, 1037, 1038],
    // KAT  53
    &[651, 652, 780, 907, 908, 1035, 1036],
    // KAT  54
    &[654, 655, 783, 910, 911, 1039],
    // KAT  55
    &[654, 655, 783, 910, 911, 1039],
    // KAT  56
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  57
    &[651, 652, 780, 907, 908, 1035, 1036],
    // KAT  58
    &[654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  59
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  60
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  61
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  62
    &[653, 654, 782, 909, 910, 1038],
    // KAT  63
    &[653, 654, 781, 782, 909, 910, 1038],
    // KAT  64
    &[653, 654, 655, 781, 782, 783, 910, 911, 1039],
    // KAT  65
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  66
    &[653, 654, 781, 782, 909, 910, 1037, 1038],
    // KAT  67
    &[653, 654, 781, 782, 909, 910, 1037, 1038],
    // KAT  68
    &[653, 654, 782, 909, 910, 1038],
    // KAT  69
    &[653, 654, 782, 909, 910, 1038],
    // KAT  70
    &[653, 654, 782, 909, 910, 1038],
    // KAT  71
    &[654, 655, 783, 910, 911, 1039],
    // KAT  72
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  73
    &[650, 651, 652, 653, 654, 779, 780, 781, 782, 909, 910, 1038],
    // KAT  74
    &[652, 653, 654, 781, 782, 909, 910, 1038],
    // KAT  75
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  76
    &[653, 654, 782, 909, 910, 1038],
    // KAT  77
    &[654, 655, 783, 910, 911, 1039],
    // KAT  78
    &[653, 654, 655, 781, 782, 783, 910, 911, 1039],
    // KAT  79
    &[654, 655, 783, 910, 911, 1039],
    // KAT  80
    &[654, 655, 783, 910, 911, 1039],
    // KAT  81
    &[653, 654, 782, 909, 910, 1038],
    // KAT  82
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  83
    &[654, 655, 783, 910, 911, 1039],
    // KAT  84
    &[654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  85
    &[654, 655, 783, 910, 911, 1039],
    // KAT  86
    &[654, 655, 782, 783, 910, 911, 1039],
    // KAT  87
    &[654, 655, 783, 910, 911, 1039],
    // KAT  88
    &[654, 655, 783, 910, 911, 1039],
    // KAT  89
    &[654, 655, 783, 910, 911, 1039],
    // KAT  90
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  91
    &[653, 654, 782, 909, 910, 1038],
    // KAT  92
    &[652, 653, 654, 655, 781, 782, 783, 910, 911, 1039],
    // KAT  93
    &[653, 654, 655, 782, 783, 910, 911, 1038, 1039],
    // KAT  94
    &[653, 654, 655, 782, 783, 910, 911, 1039],
    // KAT  95
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  96
    &[654, 655, 783, 910, 911, 1039],
    // KAT  97
    &[654, 655, 783, 910, 911, 1039],
    // KAT  98
    &[654, 655, 783, 910, 911, 1038, 1039],
    // KAT  99
    &[654, 655, 783, 910, 911, 1039],
];

fn sweep_kat(idx: usize) -> Vec<usize> {
    let (_seed, pk_hex, _sk, msg_hex, sig_hex) = KAT_VECTORS[idx];
    let pk_bytes = hex::decode(pk_hex).expect("pk hex");
    let sig = hex::decode(sig_hex).expect("sig hex");
    let msg = hex::decode(msg_hex).expect("msg hex");

    let pk_arr: &[u8; VERIFYING_KEY_BYTES] = pk_bytes.as_slice().try_into().expect("pk length");
    let vk = VerifyingKey::from_bytes(pk_arr).expect("baseline pk parses");

    let sig_arr: [u8; SIGNATURE_BYTES] = sig[..SIGNATURE_BYTES]
        .try_into()
        .expect("sig prefix present");
    let baseline_sig = Signature::from_bytes(&sig_arr).expect("baseline sig parses");
    vk.verify(&msg, &baseline_sig)
        .expect("baseline (vk, sig, msg) must verify");

    let mut accepted: Vec<usize> = Vec::new();
    for bit in 0..(SIGNATURE_BYTES * 8) {
        let mut flipped = sig_arr;
        flipped[bit / 8] ^= 1u8 << (bit % 8);
        if let Ok(s) = Signature::from_bytes(&flipped) {
            if vk.verify(&msg, &s).is_ok() {
                accepted.push(bit);
            }
        }
    }
    accepted
}

fn assert_residual_matches(idx: usize) {
    let actual = sweep_kat(idx);
    let expected = KAT_INHERENT_MALLEABLE_BITS[idx];
    let unexpected: Vec<usize> = actual
        .iter()
        .copied()
        .filter(|b| !expected.contains(b))
        .collect();
    assert!(
        unexpected.is_empty(),
        "KAT {idx}: {} unexpected single-bit sig flips still verified — \
         outside the pinned residual; investigate whether a fix added \
         malleability, bits {unexpected:?}",
        unexpected.len(),
    );
    let missing: Vec<usize> = expected
        .iter()
        .copied()
        .filter(|b| !actual.contains(b))
        .collect();
    assert!(
        missing.is_empty(),
        "KAT {idx}: previously-documented malleable bits now reject — \
         the residual has shrunk; investigate whether a fix tightened \
         the math (and shrink the pinned set), bits {missing:?}",
    );
}

/// Default-suite sweep on KAT 0. Asserts the residual matches
/// [`KAT_INHERENT_MALLEABLE_BITS[0]`].
#[test]
fn bit_flip_sweep_kat0_rejects_all_perturbations() {
    assert_residual_matches(0);
}

/// All-KATs sweep, asserting each signature's residual matches the
/// pinned entry in [`KAT_INHERENT_MALLEABLE_BITS`]. `#[ignore]` because
/// the 100 × 1184-bit sweep runs ~25 min in release; opt in via the
/// `kat` nextest profile or
/// `cargo test bit_flip_sweep_all_kats -- --ignored --nocapture`.
#[test]
#[ignore = "slow (~25 min); opt in with --ignored"]
fn bit_flip_sweep_all_kats_matches_residuals() {
    for idx in 0..KAT_VECTORS.len() {
        assert_residual_matches(idx);
    }
}
