//! Exhaustive single-bit-flip sweep on a valid signature.
//!
//! Every one of the `8 * SIGNATURE_BYTES = 1184` single-bit
//! perturbations of a canonical KAT signature must be rejected (at
//! parse or at verify time) and must never panic, with the documented
//! exception of [`KAT0_INHERENT_MALLEABLE_BITS`] (see below). A bit
//! position outside that allowlist that still verifies is signature
//! malleability the spec doesn't permit — the bit didn't contribute
//! to integrity, so an attacker who intercepts a message could rewrite
//! that bit and the recipient wouldn't notice.
//!
//! Sister test to [`malleability`](../malleability/index.html) — that
//! one mutates *typed components* (swap `n_bt` / `r_rsp`, replace
//! `curve_aux`, etc.), this one is the blind exhaustive sweep.
//!
//! ~3 min in release (`SIGNATURE_BYTES * 8 = 1184` verify calls,
//! mostly fast since parse rejects ~30% of mutations). Runs in the
//! default `cargo test` / nextest suite — no `#[ignore]`.
//!
//! # Inherent malleability on KAT 0
//!
//! KAT 0 has `(n_bt, r_rsp) = (0, 1)`. Verify therefore takes the
//! even-response branch, applying a 2-isogeny to the M_chl-transformed
//! basis on E_chl. The kernel of that 2-isogeny is generated by a
//! 2-torsion point of E_chl[2^128]; any component of the M_chl
//! entries that produces a multiple of that kernel point is absorbed
//! by the isogeny and leaves the chain output unchanged. That's six
//! byte-level malleabilities — bits 126/127 of entries `a, c`
//! (column 0) and bit 127 of entries `b, d` (column 1),
//! corresponding to sig bits `654, 655, 910, 911` and `783, 1039`.
//!
//! These are not spec violations: the spec's M_chl entry bound
//! ([§4.5][§4.5] Alg. 4.9 step 5, enforced at parse by
//! `ChallengeMatrix::parse`) is `2^(e_rsp − n_bt + 2)`, which
//! equals `2^128` for `n_bt = 0` — the full encoding range. The
//! malleability is intrinsic to the matrix-then-isogeny structure;
//! tightening the byte encoding to remove it would go beyond the
//! spec.
//!
//! The set is pinned as a constant so a future change that adds or
//! removes a residual fails this test loudly — either direction is
//! noteworthy.
//!
//! [§4.5]: https://sqisign.org/spec/sqisign-20250707.pdf#section.4.5

use sqisign_selkie::{SIGNATURE_BYTES, Signature, VERIFYING_KEY_BYTES, VerifyingKey};

// KAT vector 0 — donor for the sweep. Hex bytes are inlined (rather
// than pulled from `keys::kat_data::KAT_VECTORS`) so the test stays
// outside the `expose-internals` feature gate and runs against the
// public API exactly as a downstream user would.
const PK_HEX: &str = "07CCD21425136F6E865E497D2D4D208F0054AD81372066E817480787AAF7B2029550C89E892D618CE3230F23510BFBE68FCCDDAEA51DB1436B462ADFAF008A010B";
const SIG_HEX: &str = "84228651F271B0F39F2F19F2E8718F31ED3365AC9E5CB303AFE663D0CFC11F0455D891B0CA6C7E653F9BA2667730BB77BEFE1B1A31828404284AF8FD7BAACC010001D974B5CA671FF65708D8B462A5A84A1443EE9B5FED7218767C9D85CEED04DB0A69A2F6EC3BE835B3B2624B9A0DF68837AD00BCACC27D1EC806A44840267471D86EFF3447018ADB0A6551EE8322AB30010202";
const MSG_HEX: &str = "D81C4D8D734FCBFBEADE3D3F8A039FAA2A2C9957E835AD55B22E75BF57BB556AC8";

/// Sig bit positions for which a single-bit flip leaves verify
/// accepting on KAT 0. Inherent to KAT 0's parameter combo — see
/// the module-level docs.
const KAT0_INHERENT_MALLEABLE_BITS: &[usize] = &[654, 655, 783, 910, 911, 1039];

#[test]
fn bit_flip_sweep_kat0_rejects_all_perturbations() {
    let pk_bytes = hex::decode(PK_HEX).expect("pk hex");
    let sig_bytes = hex::decode(SIG_HEX).expect("sig hex");
    let msg = hex::decode(MSG_HEX).expect("msg hex");

    let pk_arr: &[u8; VERIFYING_KEY_BYTES] = pk_bytes.as_slice().try_into().expect("pk length");
    let vk = VerifyingKey::from_bytes(pk_arr).expect("baseline pk parses");

    let sig_arr: [u8; SIGNATURE_BYTES] = sig_bytes.as_slice().try_into().expect("sig length");
    let baseline_sig = Signature::from_bytes(&sig_arr).expect("baseline sig parses");
    vk.verify(&msg, &baseline_sig)
        .expect("baseline (vk, sig, msg) must verify");

    let mut accepted_flips: Vec<usize> = Vec::new();
    for bit in 0..(SIGNATURE_BYTES * 8) {
        let mut flipped = sig_arr;
        flipped[bit / 8] ^= 1u8 << (bit % 8);

        match Signature::from_bytes(&flipped) {
            Err(_) => continue,
            Ok(mut_sig) => {
                if vk.verify(&msg, &mut_sig).is_ok() {
                    accepted_flips.push(bit);
                }
            }
        }
    }

    let unexpected: Vec<usize> = accepted_flips
        .iter()
        .copied()
        .filter(|b| !KAT0_INHERENT_MALLEABLE_BITS.contains(b))
        .collect();
    assert!(
        unexpected.is_empty(),
        "{} unexpected single-bit sig flips on KAT 0 still verified — \
         outside the documented inherent set, bits {:?}",
        unexpected.len(),
        unexpected
    );

    let missing: Vec<usize> = KAT0_INHERENT_MALLEABLE_BITS
        .iter()
        .copied()
        .filter(|b| !accepted_flips.contains(b))
        .collect();
    assert!(
        missing.is_empty(),
        "previously-documented inherent malleable bits on KAT 0 now reject — \
         the residual set has shrunk; investigate whether a fix changed the \
         underlying math (and update the allowlist), bits {:?}",
        missing
    );
}
