//! Negative and vulnerability test vectors for SQIsign.
//!
//! Loads test vectors from `tests/vectors/*.json` in the
//! [C2SP/wycheproof](https://github.com/C2SP/wycheproof) JSON format.
//! Covers verification negatives, keygen correctness, and sk parsing
//! robustness — rejection paths that KAT vectors (all valid) don't
//! exercise.
//!
//! Invalid vectors are independently generated by perturbation (no
//! dependency on the C reference). Valid vectors cite the C reference
//! KAT file as provenance. We intend to upstream these to C2SP/wycheproof
//! once independently-generated valid vectors are available via Sage.
//!
//! Uses only the public API — no `bench-internals` feature required.
//! Other SQIsign implementations can reuse `tests/vectors/*.json` by
//! writing their own test runner against the same schema.

use sqisign_selkie::{SIGNATURE_BYTES, SIGNING_KEY_BYTES, Signature, SigningKey, VerifyingKey};

// =====================================================================
// JSON schema types (C2SP/wycheproof signatures_common format)
// =====================================================================

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct TestFile {
    algorithm: String,
    number_of_tests: usize,
    test_groups: Vec<TestGroup>,
}

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct TestGroup {
    public_key: PublicKey,
    tests: Vec<TestVector>,
}

#[derive(serde::Deserialize)]
struct PublicKey {
    pk: String,
}

#[derive(serde::Deserialize)]
struct TestVector {
    #[serde(rename = "tcId")]
    tc_id: u32,
    comment: String,
    msg: String,
    sig: String,
    result: String,
    #[allow(dead_code)] // parsed for completeness; runner doesn't branch on flags yet
    flags: Vec<String>,
}

// =====================================================================
// Helpers
// =====================================================================

/// Returns `true` if `vk.verify(msg, sig)` succeeds.
///
/// Uses `catch_unwind` because some corruption paths currently
/// trigger `debug_assert!` panics in the (2,2)-isogeny splitting
/// step instead of returning `Err`. Both panic and `Err` count as
/// rejection for "invalid" vectors.
///
/// TODO: Once `GetIndexSplitting` returns `Option` instead of
/// panicking, remove the `catch_unwind` and test for `Err` directly.
fn verify_succeeds(vk: &VerifyingKey, msg: &[u8], sig: &Signature) -> bool {
    let vk = *vk;
    let sig = *sig;
    let msg = msg.to_vec();
    matches!(
        std::panic::catch_unwind(move || vk.verify(&msg, &sig)),
        Ok(Ok(()))
    )
}

// =====================================================================
// Test runner
// =====================================================================

#[test]
fn sqisign_verify_vectors() {
    let json = include_str!("vectors/sqisign_verify.json");
    let file: TestFile = serde_json::from_str(json).expect("failed to parse test vectors");

    assert_eq!(file.algorithm, "SQIsign_248");

    let mut tested = 0;

    for group in &file.test_groups {
        let pk_bytes = hex::decode(&group.public_key.pk).unwrap();
        let vk = match pk_bytes.as_slice().try_into() {
            Err(_) => {
                // pk wrong length — all tests in this group must be invalid
                for tv in &group.tests {
                    assert_eq!(
                        tv.result, "invalid",
                        "tcId {}: pk parse failed (wrong length) but result is {}",
                        tv.tc_id, tv.result
                    );
                    tested += 1;
                }
                continue;
            }
            Ok(arr) => match VerifyingKey::from_bytes(arr) {
                Err(_) => {
                    for tv in &group.tests {
                        assert_eq!(
                            tv.result, "invalid",
                            "tcId {}: pk parse failed but result is {}",
                            tv.tc_id, tv.result
                        );
                        tested += 1;
                    }
                    continue;
                }
                Ok(vk) => vk,
            },
        };

        for tv in &group.tests {
            let msg = hex::decode(&tv.msg).unwrap();
            let sig_bytes = hex::decode(&tv.sig).unwrap();

            match tv.result.as_str() {
                "valid" => {
                    let sig_arr: &[u8; SIGNATURE_BYTES] =
                        sig_bytes.as_slice().try_into().unwrap_or_else(|_| {
                            panic!("tcId {}: sig wrong length {}", tv.tc_id, sig_bytes.len())
                        });
                    let sig = Signature::from_bytes(sig_arr)
                        .unwrap_or_else(|e| panic!("tcId {}: sig parse failed: {e}", tv.tc_id));
                    assert!(
                        verify_succeeds(&vk, &msg, &sig),
                        "tcId {}: expected valid, got rejection ({})",
                        tv.tc_id,
                        tv.comment
                    );
                }
                "invalid" => {
                    // Parse may fail (which is fine) or succeed.
                    // If parse succeeds, verify must reject.
                    let sig_arr: Result<&[u8; SIGNATURE_BYTES], _> =
                        sig_bytes.as_slice().try_into();
                    let rejected = match sig_arr {
                        Err(_) => true, // wrong length — rejected at parse
                        Ok(arr) => match Signature::from_bytes(arr) {
                            Err(_) => true, // structural rejection
                            Ok(sig) => !verify_succeeds(&vk, &msg, &sig),
                        },
                    };
                    assert!(
                        rejected,
                        "tcId {}: expected invalid, but verified ({})",
                        tv.tc_id, tv.comment
                    );
                }
                "acceptable" => {
                    // Either outcome is fine — just ensure no panic
                    // outside catch_unwind.
                    let _ = sig_bytes.as_slice().try_into().ok().and_then(
                        |arr: &[u8; SIGNATURE_BYTES]| {
                            Signature::from_bytes(arr)
                                .ok()
                                .map(|sig| verify_succeeds(&vk, &msg, &sig))
                        },
                    );
                }
                other => panic!("tcId {}: unknown result {:?}", tv.tc_id, other),
            }

            tested += 1;
        }
    }

    assert_eq!(
        tested, file.number_of_tests,
        "verify numberOfTests mismatch: ran {tested}, expected {}",
        file.number_of_tests
    );
}

// =====================================================================
// Keygen / sk parsing vectors
// =====================================================================

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct KeygenTestFile {
    algorithm: String,
    number_of_tests: usize,
    test_groups: Vec<KeygenTestGroup>,
}

#[derive(serde::Deserialize)]
struct KeygenTestGroup {
    tests: Vec<KeygenTestVector>,
}

#[derive(serde::Deserialize)]
struct KeygenTestVector {
    #[serde(rename = "tcId")]
    tc_id: u32,
    comment: String,
    #[allow(dead_code)] // used by deterministic keygen tests (currently #[ignore])
    #[serde(default)]
    seed: Option<String>,
    #[serde(default)]
    pk: Option<String>,
    sk: String,
    result: String,
    #[allow(dead_code)]
    flags: Vec<String>,
}

#[test]
fn sqisign_keygen_vectors() {
    let json = include_str!("vectors/sqisign_keygen.json");
    let file: KeygenTestFile = serde_json::from_str(json).expect("failed to parse keygen vectors");

    assert_eq!(file.algorithm, "SQIsign_248");

    let mut tested = 0;

    for group in &file.test_groups {
        for tv in &group.tests {
            let sk_bytes = hex::decode(&tv.sk).unwrap();

            match tv.result.as_str() {
                "valid" => {
                    // sk must parse
                    let sk_arr: &[u8; SIGNING_KEY_BYTES] =
                        sk_bytes.as_slice().try_into().unwrap_or_else(|_| {
                            panic!("tcId {}: sk wrong length {}", tv.tc_id, sk_bytes.len())
                        });
                    let sk = SigningKey::from_bytes(sk_arr)
                        .unwrap_or_else(|e| panic!("tcId {}: sk parse failed: {e}", tv.tc_id));

                    // If pk is provided, the embedded vk must match
                    if let Some(pk_hex) = &tv.pk {
                        let expected_pk = hex::decode(pk_hex).unwrap();
                        assert_eq!(
                            sk.verifying_key().to_bytes().as_slice(),
                            expected_pk.as_slice(),
                            "tcId {}: pk mismatch ({})",
                            tv.tc_id,
                            tv.comment
                        );
                    }

                    // Deterministic keygen vectors (with seed) are
                    // #[ignore] because keygen is slow. The sk/pk
                    // consistency is checked above without running
                    // keygen.
                }
                "invalid" => {
                    // Parse must fail (wrong length or structural).
                    let rejected = match sk_bytes.as_slice().try_into() {
                        Err(_) => true, // wrong length
                        Ok(arr) => {
                            let arr: &[u8; SIGNING_KEY_BYTES] = arr;
                            SigningKey::from_bytes(arr).is_err()
                        }
                    };
                    // If parse succeeds despite our expectation, the
                    // vector is "invalid" in the sense that signing
                    // with it should fail or produce non-verifiable
                    // signatures. For now we only check parse
                    // rejection; signing tests come later.
                    if !rejected {
                        // Parse succeeded — this is acceptable for
                        // some "invalid" vectors (e.g., bit flips in
                        // the ideal that don't violate structural
                        // constraints but produce a wrong key).
                        // TODO: once signing works, verify that
                        // signing with a parsed "invalid" sk produces
                        // signatures that don't verify.
                    }
                }
                "acceptable" => {
                    // Either outcome is fine.
                }
                other => panic!("tcId {}: unknown result {:?}", tv.tc_id, other),
            }

            tested += 1;
        }
    }

    assert_eq!(
        tested, file.number_of_tests,
        "keygen numberOfTests mismatch: ran {tested}, expected {}",
        file.number_of_tests
    );
}

// =====================================================================
// Signing vectors (skeleton — signing is in flux)
// =====================================================================

#[derive(serde::Deserialize)]
#[serde(rename_all = "camelCase")]
struct SignTestFile {
    algorithm: String,
    number_of_tests: usize,
    test_groups: Vec<SignTestGroup>,
}

#[derive(serde::Deserialize)]
struct SignTestGroup {
    tests: Vec<SignTestVector>,
}

#[derive(serde::Deserialize)]
struct SignTestVector {
    #[serde(rename = "tcId")]
    tc_id: u32,
    comment: String,
    #[allow(dead_code)] // will be used once sign-then-verify round-trips are wired up
    sk: String,
    pk: String,
    msg: String,
    sig: String,
    result: String,
    #[allow(dead_code)]
    flags: Vec<String>,
}

/// Signing test vectors. Currently validates that KAT signatures
/// verify under their paired pk (the sign-then-verify contract from
/// the C reference). Will grow as our signer stabilizes.
#[test]
fn sqisign_sign_vectors() {
    let json = include_str!("vectors/sqisign_sign.json");
    let file: SignTestFile = serde_json::from_str(json).expect("failed to parse sign vectors");

    assert_eq!(file.algorithm, "SQIsign_248");

    let mut tested = 0;

    for group in &file.test_groups {
        for tv in &group.tests {
            let pk_bytes = hex::decode(&tv.pk).unwrap();
            let vk = VerifyingKey::from_bytes(
                pk_bytes
                    .as_slice()
                    .try_into()
                    .unwrap_or_else(|_| panic!("tcId {}: pk wrong length", tv.tc_id)),
            )
            .unwrap_or_else(|e| panic!("tcId {}: pk parse failed: {e}", tv.tc_id));

            let msg = hex::decode(&tv.msg).unwrap();
            let sig_bytes = hex::decode(&tv.sig).unwrap();

            match tv.result.as_str() {
                "valid" => {
                    let sig_arr: &[u8; SIGNATURE_BYTES] =
                        sig_bytes.as_slice().try_into().unwrap_or_else(|_| {
                            panic!("tcId {}: sig wrong length {}", tv.tc_id, sig_bytes.len())
                        });
                    let sig = Signature::from_bytes(sig_arr)
                        .unwrap_or_else(|e| panic!("tcId {}: sig parse failed: {e}", tv.tc_id));
                    assert!(
                        verify_succeeds(&vk, &msg, &sig),
                        "tcId {}: expected valid, got rejection ({})",
                        tv.tc_id,
                        tv.comment
                    );
                    // TODO: once signing stabilizes, also:
                    // 1. sign(sk, msg) and verify the result
                    // 2. check NonceIndependence (distinct E_com)
                    // 3. check response edge cases (r_rsp, n_bt)
                }
                "invalid" => {
                    let rejected = match sig_bytes.as_slice().try_into() {
                        Err(_) => true,
                        Ok(arr) => match Signature::from_bytes(arr) {
                            Err(_) => true,
                            Ok(sig) => !verify_succeeds(&vk, &msg, &sig),
                        },
                    };
                    assert!(
                        rejected,
                        "tcId {}: expected invalid, but verified ({})",
                        tv.tc_id, tv.comment
                    );
                }
                "acceptable" => {}
                other => panic!("tcId {}: unknown result {:?}", tv.tc_id, other),
            }

            tested += 1;
        }
    }

    assert_eq!(
        tested, file.number_of_tests,
        "sign numberOfTests mismatch: ran {tested}, expected {}",
        file.number_of_tests
    );
}
