events {}
http {
    include mime.types;
    sendfile on;

    server {
        listen 8080;
        listen [::]:8080;
        port_in_redirect off;

        resolver 127.0.0.11;
        autoindex off;

        server_name _;
        server_tokens off;

        root /app;
        gzip_static on;

        location /coverage/ {
            alias /data/coverage/;
        }

        location /bench/ {
            alias /data/bench/;
        }

        location /mutants/ {
            alias /data/mutants/;
        }

        location /dudect/ {
            alias /data/dudect/;
        }

        location /tacet/ {
            alias /data/tacet/;
        }

        location /kat/ {
            alias /data/kat/;
        }

        error_page 404 /404.html;
        location = /404.html {
          internal;
        }

        location /metrics {
           stub_status on;
        }
    }
}
