#!/usr/bin/env bash
# Regenerates the committed PGO profile for the host target triple
# and copies it into tools/pgo/<triple>.profdata.
#
# The committed profiles in tools/pgo/ are first-class build inputs:
# .cargo/config.toml passes `-Cprofile-use=tools/pgo/<triple>.profdata`
# in each target's rustflags, so plain `cargo build --release` is the
# PGO-optimized build for downstream consumers (no per-machine training
# run needed). Profile data is LLVM-version-keyed, so re-run this
# script after any rustc bump or training-corpus edit, then commit
# the resulting .profdata.
#
# This script only generates for the HOST target. Non-host triples
# (e.g. x86_64-unknown-linux-gnu when run on aarch64-apple-darwin)
# are regenerated by the corresponding CI runner in
# .github/workflows/pgo.yml, which commits via a follow-up PR.
#
# Usage:
#   scripts/regenerate-pgo.sh           # 100 training seeds (default)
#   scripts/regenerate-pgo.sh 200       # more seeds (diminishing returns past ~100)
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/.." && pwd)"
seeds="${1:-100}"

driver="$(mktemp -t pgo-build-XXXXXX)"
trap 'rm -f "$driver"' EXIT
rustc -O "$repo/.github/scripts/pgo-build.rs" -o "$driver"

# `generate` forces a fresh instrument + train + merge, overwriting
# the cached target/pgo/<triple>.profdata.
"$driver" generate "$seeds"

triple=$("$driver" flags | awk '/^triple:/{print $2}')
src="$repo/target/pgo/$triple.profdata"
dst="$repo/tools/pgo/$triple.profdata"
mkdir -p "$(dirname "$dst")"
cp "$src" "$dst"

echo "[regenerate-pgo] wrote $dst ($(wc -c <"$dst") bytes)"
echo "[regenerate-pgo] commit tools/pgo/$triple.profdata if it changed."
