//! The Deuring correspondence: converting between ideals and isogenies.
//!
//! This module bridges the quaternion algebra world ([`crate::quaternions`])
//! and the elliptic curve world ([`crate::curves`], [`crate::surfaces`]).
//! The Deuring correspondence establishes a bijection between left ideals
//! of a maximal order O ⊂ B_{p,∞} and separable isogenies from E where
//! End(E) ≅ O.
//!
//! The main algorithms are:
//! - [`IdealToIsogeny`][Alg. 3.13] (Algorithm 3.13): convert an O₀-ideal to an
//!   isogeny and its images on torsion points
//! - [`FixedDegreeIsogeny`][Alg. 3.15] (Algorithm 3.15): compute an isogeny of
//!   prescribed degree from precomputed data
//! - [`SuitableIdeals`][Alg. 3.16] (Algorithm 3.16): decompose an ideal into
//!   pieces with coprime odd norms
//!
//! See [§3.2] of the SQIsign specification.
//!
//! [§3.2]: https://sqisign.org/spec/sqisign-20250707.pdf#section.3.2
//! [Alg. 3.13]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
//! [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
//! [Alg. 3.16]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16

pub(crate) mod endomorphism;
pub(crate) mod precomputed;

use endomorphism::ActionMatrix;
use precomputed::ACTION_MATRICES;

use crate::{
    curves::{
        TorsionBasis, TorsionExponent,
        isogeny::{IsogenyDegree, Kernel as CurveKernel},
        montgomery::{Curve, ProjectiveXOnlyPoint},
        scalar::Scalar,
    },
    params::QUAT_REPRES_BOUND_INPUT,
    quaternions::{
        algebra::{Coordinate, Denominator, Element},
        bigint::BigInt,
        lattice::{ExtremalOrder, Lattice, LeftIdeal},
        precomputed::{CONNECTING_IDEAL_NORMS, EXTREMAL_ORDERS},
    },
    surfaces,
};

/// A kernel generator decomposed in a torsion basis (P, Q).
///
/// Represents the point [a]P + [b]Q where a, b are scalars. The
/// actual curve point is computed by evaluating the scalars against
/// a specific torsion basis.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KernelDecomposition {
    /// Coefficient of P.
    pub a: Scalar,
    /// Coefficient of Q.
    pub b: Scalar,
}

/// Extension trait for computing endomorphism action matrices
/// from quaternion elements already expressed in the order basis.
///
/// Given an element with coordinates (c₀, c₁, c₂, c₃) in the order
/// basis, computes M_α = c₀·M₁ + c₁·M₂ + c₂·M₃ + c₃·M₄ (mod 2^f).
///
/// See §3.2.1.1 of the spec.
pub trait DeuringAction {
    /// Compute the action matrix given four order-basis action matrices.
    ///
    /// The element's (a, b, c, d) coordinates are used as coefficients.
    /// The caller must ensure the element is expressed in the order basis,
    /// not the {1, i, j, k} basis.
    fn action_matrix(&self, basis_matrices: &[ActionMatrix; 4], f: TorsionExponent)
    -> ActionMatrix;
}

impl DeuringAction for Element<4> {
    fn action_matrix(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        f: TorsionExponent,
    ) -> ActionMatrix {
        let coords = [
            *self.a.as_bigint(),
            *self.b.as_bigint(),
            *self.c.as_bigint(),
            *self.d.as_bigint(),
        ];
        let mut result = ActionMatrix::ZERO;
        for i in 0..4 {
            result = result.add_scaled_mod(&coords[i], &basis_matrices[i], f.value());
        }
        result
    }
}

/// Extension trait for converting an ideal to a kernel generator
/// via the Deuring correspondence.
///
/// See [Alg. 3.14] from the spec.
///
/// [Alg. 3.14]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.14
pub trait IdealKernel {
    /// Compute the kernel decomposition for this ideal of norm 2^e.
    ///
    /// Returns scalars (a, b) such that ker φ_I is generated by
    /// [a·2^{f-e}]P₀ + [b·2^{f-e}]Q₀, where (P₀, Q₀) is the
    /// precomputed torsion basis of E₀[2^f].
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition>;
}

impl IdealKernel for LeftIdeal<4> {
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition> {
        // Mirrors C-ref's `id2iso_ideal_to_kernel_dlogs_even`
        // (`id2iso.c:29-86`):
        //
        //   1. α = lideal_generator(I).
        //   2. α := conj(α).             ← Selkie was MISSING this step.
        //   3. Express α in O₀-basis coords c₀, c₁, c₂, c₃.
        //   4. Build 2×2 matrix: mat[i][j] = c₀·δ_{i,j}  +  c₁·GEN2[i][j]
        //                                 + c₂·GEN3[i][j]
        //                                 + c₃·GEN4[i][j]
        //   5. (s, t) ← column 0 of mat (mod norm). If gcd(s, t) is even, use column 1
        //      instead.   ← Selkie was finding the KERNEL of M_α, which is the wrong
        //      operation. C-ref takes a column directly.
        //
        // Step 1: Find α ∈ O₀ such that I = O₀⟨α, 2^e⟩.
        let alpha = match self.generator() {
            Some(a) => a,
            None => {
                #[cfg(test)]
                eprintln!("[to_kernel] DROP: self.generator() returned None");
                return None;
            }
        };

        // Step 2: Conjugate.
        let alpha_conj = alpha.conjugate();

        // Steps 3-4: Compute M_{conj(α)} mod norm = 2^e.
        let m_alpha = alpha_conj.action_matrix(basis_matrices, e);

        // Step 5: Pick column 0; if gcd(s, t) is even, use column 1.
        let modulus = BigInt::<4>::ONE.shl(e.value());
        let s0 = BigInt::<4>::from(*m_alpha.entry(0, 0)).ct_mod(&modulus);
        let t0 = BigInt::<4>::from(*m_alpha.entry(1, 0)).ct_mod(&modulus);
        let g0 = s0.gcd(&t0);
        // `ibz_is_even`: low bit zero.
        let g0_is_even = g0.as_limbs()[0] & 1 == 0;
        let (s, t) = if g0_is_even {
            let s1 = BigInt::<4>::from(*m_alpha.entry(0, 1)).ct_mod(&modulus);
            let t1 = BigInt::<4>::from(*m_alpha.entry(1, 1)).ct_mod(&modulus);
            (s1, t1)
        } else {
            (s0, t0)
        };
        Some(KernelDecomposition {
            a: Scalar::from(s),
            b: Scalar::from(t),
        })
    }
}

// KernelToIdeal (Algorithm 3.17) is TorsionBasis::kernel_to_ideal() in
// curves/mod.rs.

/// Compute the even (non-backtracking) response isogeny.
///
/// Given curve E_chl with torsion basis (P, Q), quaternion α,
/// and integers e' (= e'_rsp) and r (= r_rsp), computes the
/// even response isogeny φ^even_rsp : E_chl → E.
///
/// Returns the codomain curve E and the images P', Q' of the
/// basis points.
///
/// Implements [ComputeEvenNonBacktrackingResponse][Alg. 4.6].
///
/// [Alg. 4.6]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.4.6
pub fn compute_even_response(
    _curve: &Curve,
    P: &ProjectiveXOnlyPoint,
    Q: &ProjectiveXOnlyPoint,
    PmQ: &ProjectiveXOnlyPoint,
    alpha: &Element<4>,
    e_prime: TorsionExponent,
    r_rsp: TorsionExponent,
) -> Option<(
    Curve,
    ProjectiveXOnlyPoint,
    ProjectiveXOnlyPoint,
    ProjectiveXOnlyPoint,
)> {
    let e_prime = e_prime.value();
    let r_rsp = r_rsp.value();

    // Step 1: I = O₀·conj(α) + O₀·(2^r)
    //
    // C-ref's sign.c line 401 conjugates `resp_quat` in place before
    // calling `quat_lideal_create(lideal_resp_two, resp_quat, 2^r, O₀)`
    // at line 616. So `lideal_resp_two = O₀·conj(α_response) + O₀·(2^r)`.
    // We construct the same lattice here so that `ideal.generator()`
    // enumerates over the same basis as C-ref's `quat_lideal_generator`.
    let norm = BigInt::<4>::ONE.shl(r_rsp);
    let alpha_for_ideal = alpha.conjugate();
    let ideal = LeftIdeal::new(&alpha_for_ideal, &norm, EXTREMAL_ORDERS[0].order());

    // Step 2: (s, t) ← IdealToKernel(I)
    let basis_mats = [
        ACTION_MATRICES[0][3], // gen2 = action of i
        ACTION_MATRICES[0][4], // gen3 = action of (i+j)/2
        ACTION_MATRICES[0][5], // gen4 = action of (1+k)/2
    ];
    // Inline C-ref's `id2iso_ideal_to_kernel_dlogs_even` (id2iso.c:29-86).
    //
    // C-ref calls `quat_lideal_generator(lideal_resp_two)` to pick a
    // SMALL generator α of the response ideal by enumerating
    // (a, b, c, d) with |a|+|b|+|c|+|d| = n increasing. We must do
    // the SAME to match — the kernel of `α | E[2^r]` is NOT invariant
    // under α → α·u for non-trivial units u ∈ O_R(I)* (which include
    // ±i in O₀), so a different generator yields a different kernel
    // subgroup and thus a different `j(E_chl_3)`.
    //
    // `ideal.generator()` mirrors C-ref's `quat_lideal_generator`.
    let alpha_for_kernel = match ideal.generator() {
        Some(g) => g,
        None => {
            #[cfg(test)]
            eprintln!("[compute_even_response] DROP: ideal.generator() None");
            return None;
        }
    };
    let alpha_conj = alpha_for_kernel.conjugate();
    let m_alpha = action_matrix(
        &alpha_conj,
        EXTREMAL_ORDERS[0].order(),
        &basis_mats,
        TorsionExponent::try_from(r_rsp).ok()?,
    )?;
    let modulus = BigInt::<4>::ONE.shl(r_rsp);
    let s0 = BigInt::<4>::from(*m_alpha.entry(0, 0)).ct_mod(&modulus);
    let t0 = BigInt::<4>::from(*m_alpha.entry(1, 0)).ct_mod(&modulus);
    let g0 = s0.gcd(&t0);
    let g0_is_even = g0.as_limbs()[0] & 1 == 0;
    let (s, t) = if g0_is_even {
        let s1 = BigInt::<4>::from(*m_alpha.entry(0, 1)).ct_mod(&modulus);
        let t1 = BigInt::<4>::from(*m_alpha.entry(1, 1)).ct_mod(&modulus);
        (s1, t1)
    } else {
        (s0, t0)
    };
    let _ = KernelDecomposition {
        a: Scalar::from(s),
        b: Scalar::from(t),
    };

    // Step 3: Double the basis down to order 2^r_rsp, then compute
    // K = [s]P + [t]Q on the reduced basis.
    //
    // C ref (`compute_small_chain_isogeny_signature`, sign.c:627–632):
    //   ec_dbl_iter_basis(B_chall_2, pow_dim2_deg_resp + HD_extra_torsion,
    //                     B_chall_2, E_chall_2);
    //   ec_biscalar_mul_ibz_vec(&ker, &vec_resp_two, /* f = */ length,
    //                           B_chall_2, E_chall_2);
    //
    // Equivalent mathematically to `[s · 2^(e' + 2)]P + [t · 2^(e' + 2)]Q`
    // on the un-reduced basis (the prior implementation), but the
    // 3-pt ladder's projective (X : Z) representative depends on the
    // *path*: a long ladder at order 2^reduced_order versus a short
    // ladder at order 2^r_rsp produces byte-different reps of the
    // same abstract point. Downstream `isogeny_small` is sensitive to
    // the projective rep (same kernel subgroup, different (X : Z) →
    // different chain codomain rep).
    let shift = e_prime + 2;
    let basis_reduced = {
        let mut Pr = *P;
        let mut Qr = *Q;
        let mut Rr = *PmQ;
        for _ in 0..shift {
            Pr = Pr.double();
            Qr = Qr.double();
            Rr = Rr.double();
        }
        TorsionBasis::from_propagated(Pr, Qr, Rr)
    };
    let s_scalar = Scalar::from(s);
    let t_scalar = Scalar::from(t);
    let K =
        basis_reduced.biscalar_mul(&s_scalar, &t_scalar, TorsionExponent::try_from(r_rsp).ok()?);

    // Step 4: E', {P', Q', PmQ'} ← TwoisogenyChainSmall(K, E, r, {P, Q, PmQ}, true)
    //
    // Push `PmQ` as a third evaluated point so the codomain basis
    // carries a propagated difference; downstream
    // `compute_challenge_isogeny` and `ChangeOfBasisMatrix::from_bases`
    // require `PmQ` consistent with `P` and `Q`'s evaluation history.
    let isogeny_res = CurveKernel::new(K).isogeny_small(
        TorsionExponent::try_from(r_rsp).ok()?,
        &[*P, *Q, *PmQ],
        true,
    );
    let (new_curve, images) = match isogeny_res {
        Ok(r) => r,
        Err(e) => {
            #[cfg(test)]
            eprintln!(
                "[compute_even_response] DROP: isogeny_small err: {e:?}, r_rsp={r_rsp}, e_prime={e_prime}"
            );
            return None;
        }
    };

    Some((new_curve, images[0], images[1], images[2]))
}

// ---------------------------------------------------------------------------
// CurveWithEndomorphismRing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// IdealToIsogeny (Algorithm 3.13) + FixedDegreeIsogeny (Algorithm 3.15)
// ---------------------------------------------------------------------------

/// Compute the action matrix M_α for an element α on E_t[2^f],
/// given the order's lattice and generator action matrices.
///
/// Decomposes α from {1,i,j,k} into the order's column basis
/// (c₀, c₁, c₂, c₃), then assembles:
///
/// M_α = c₀ · I + c₁ · M_{gen2} + c₂ · M_{gen3} + c₃ · M_{gen4}  (mod 2^f)
fn action_matrix(
    elem: &Element<4>,
    order: &Lattice<4>,
    gen_matrices: &[ActionMatrix; 3],
    f: TorsionExponent,
) -> Option<ActionMatrix> {
    // Decompose at width 20 — for p-extremal orders with `q ≥ 5`
    // the basis entries reach ~250 bits (e.g. q=97 row 1 col 3 ≈
    // 2^250), and `Lattice::decompose` computes a 4×4 adjugate whose
    // 3×3 minors accumulate up to ~3·250 = 750 bits. Then
    // `adjugate · rhs` (rhs ≈ basis_entry ≈ 250 bits) reaches ~1000
    // bits before `/ det`. Width 8 silently overflows; width 20 is
    // comfortable margin for all NIST-I orders. Same width pitfall
    // as `ExtremalOrder::represent_integer`.
    let elem_w = Element::<20>::new(
        Coordinate::from_bigint(elem.a.as_bigint().widen::<20>()),
        Coordinate::from_bigint(elem.b.as_bigint().widen::<20>()),
        Coordinate::from_bigint(elem.c.as_bigint().widen::<20>()),
        Coordinate::from_bigint(elem.d.as_bigint().widen::<20>()),
        Denominator::from_bigint_unchecked(BigInt::<4>::from(elem.denom).widen::<20>()),
    );
    let order_w: Lattice<20> = {
        let basis4 = order.basis();
        let mut basis_w = crate::quaternions::linear::Matrix::<20>::ZERO;
        for row in 0..4 {
            for col in 0..4 {
                basis_w[row][col] = basis4[row][col].widen::<20>();
            }
        }
        Lattice::new(basis_w, order.denom().widen::<20>())
    };
    let coords_w = order_w.decompose(&elem_w)?;
    let coords: [BigInt<4>; 4] = [
        coords_w[0].narrow_to::<4>()?,
        coords_w[1].narrow_to::<4>()?,
        coords_w[2].narrow_to::<4>()?,
        coords_w[3].narrow_to::<4>()?,
    ];
    #[cfg(test)]
    {
        crate::selkie_trace!("CREF_FDI coeffs[0]={}", coords[0]);
        crate::selkie_trace!("CREF_FDI coeffs[1]={}", coords[1]);
        crate::selkie_trace!("CREF_FDI coeffs[2]={}", coords[2]);
        crate::selkie_trace!("CREF_FDI coeffs[3]={}", coords[3]);
    }

    // Reduce all coefficients mod 2^f. For negative coefficients,
    // ct_mod returns a negative remainder (truncated division), so
    // add the modulus to get the canonical representative in [0, 2^f).
    let modulus = BigInt::<4>::ONE.shl(f.value());
    let reduce = |c: &BigInt<4>| -> Scalar {
        let r = c.ct_mod(&modulus);
        if bool::from(r.is_negative()) {
            Scalar::from(r.ct_add(&modulus))
        } else {
            Scalar::from(r)
        }
    };

    let c0_scalar = reduce(&coords[0]);
    let mut result = ActionMatrix::new(c0_scalar, Scalar::ZERO, Scalar::ZERO, c0_scalar);

    for k in 0..3 {
        let s = reduce(&coords[k + 1]);
        let other = &gen_matrices[k];
        let fv = f.value();
        result = ActionMatrix::new(
            result
                .entry(0, 0)
                .add_mod2k(&s.mul_mod2k(other.entry(0, 0), fv), fv),
            result
                .entry(0, 1)
                .add_mod2k(&s.mul_mod2k(other.entry(0, 1), fv), fv),
            result
                .entry(1, 0)
                .add_mod2k(&s.mul_mod2k(other.entry(1, 0), fv), fv),
            result
                .entry(1, 1)
                .add_mod2k(&s.mul_mod2k(other.entry(1, 1), fv), fv),
        );
    }

    Some(result)
}

/// Compute a u-isogeny from E_t via a (2,2)-isogeny chain.
///
/// [FixedDegreeIsogeny][Alg. 3.15] (Algorithm [3.15][Alg. 3.15]):
/// given a positive odd [`IsogenyDegree`] u < 2^{f−2} and the
/// precomputed data for curve E_t, finds an endomorphism θ of E_t
/// with nrd(θ) = u·(2^{e_FDI} − u), then computes a
/// (2^{e_FDI}, 2^{e_FDI})-isogeny on E_t × E_t whose projection
/// gives the u-isogeny φ: E_t → E.
///
/// Returns `(E, φ(P_t), φ(Q_t))`.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls RepresentInteger (variable-time
/// search) and the (2,2)-chain length depends on e_FDI.
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived (u, t) values during signing (Algorithm 4.2 via
/// IdealToIsogeny).
///
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
fn fixed_degree_isogeny<R: rand_core::RngCore>(
    order: &'static ExtremalOrder<4>,
    u: &IsogenyDegree,
    rng: &mut R,
) -> Option<(
    Curve,
    ProjectiveXOnlyPoint,
    ProjectiveXOnlyPoint,
    ProjectiveXOnlyPoint,
)> {
    let f = TorsionExponent::FULL;
    let p_bits = 251u32; // ⌈log₂(p)⌉ for NIST-I

    // Look up the precomputed curve and torsion basis for this order.
    // `EXTREMAL_ORDERS.len() == ExtremalCurve::ALL.len()` is enforced
    // at compile time in `precomputed.rs`, so the `try_from` below
    // cannot fail for any `t` returned by `.position()`.
    let t = EXTREMAL_ORDERS.iter().position(|o| o.q() == order.q())?;
    let curve_idx = precomputed::torsion_basis::ExtremalCurve::try_from(t)
        .expect("EXTREMAL_ORDERS length matches ExtremalCurve::ALL by compile-time assert");

    let (px, qx, pmq_x, a_coeff) = curve_idx.basis();
    #[cfg(test)]
    crate::selkie_trace!("[FDI] t={t}, e_fdi will be computed next");
    let curve_t = if curve_idx == precomputed::torsion_basis::ExtremalCurve::E0 {
        Curve::E0
    } else {
        Curve::from(crate::curves::montgomery::Coefficient::from(a_coeff))
    };
    let p_t = ProjectiveXOnlyPoint::from_affine_x(px, &curve_t);
    let q_t = ProjectiveXOnlyPoint::from_affine_x(qx, &curve_t);
    let pmq_t = ProjectiveXOnlyPoint::from_affine_x(pmq_x, &curve_t);
    // The biladder's three-point ladder requires a PmQ whose
    // projective representative is consistent with the precomputed
    // action matrices. Computing PmQ via `projective_difference`
    // picks a different representative that causes the
    // Okeya-Sakurai lift to recover the wrong y-sign.
    let basis_t = TorsionBasis::from_propagated(p_t, q_t, pmq_t);
    // CT linear-scan over all seven candidate rows. `curve_idx` is
    // derived from the secret signing-key ideal's right order
    // (Algorithm 4.2, line 7 `I_sig_response → right_order`), so the
    // lookup must not depend on the index through memory access.
    let gen_matrices = curve_idx.gen_matrices();

    // Step 1: e_FDI = min(f − 2, ⌈log₂(p)⌉ − ⌈log₂(u)⌉ + QUAT_repres_bound_input)
    let e_fdi = core::cmp::min(
        f.value() - 2,
        p_bits.saturating_sub(u.bit_length()) + QUAT_REPRES_BOUND_INPUT,
    );

    // Step 2: θ ← RepresentInteger(u·(2^{e_FDI} − u), O_t, true)
    let u_wide = u.to_bigint_wide();
    let two_e_fdi = BigInt::<8>::ONE.shl(e_fdi);
    // If u ≥ 2^{e_FDI}, the product is non-positive — no solution.
    if u_wide >= two_e_fdi {
        return None;
    }
    let m = u_wide.ct_mul(&two_e_fdi.ct_sub(&u_wide));
    let order_wide = ExtremalOrder::<8>::from(*order);
    let theta = match order_wide.represent_integer(&m, true, rng) {
        Some(t) => {
            #[cfg(test)]
            {
                crate::selkie_trace!("[FDI] represent_integer OK, e_fdi={e_fdi}");
                crate::selkie_trace!("THETA_RAW coord0={}", t.a);
                crate::selkie_trace!("THETA_RAW coord1={}", t.b);
                crate::selkie_trace!("THETA_RAW coord2={}", t.c);
                crate::selkie_trace!("THETA_RAW coord3={}", t.d);
                crate::selkie_trace!("THETA_RAW denom={}", t.denom);
                crate::selkie_trace!("THETA_RAW u={}", BigInt::<4>::from(*u));
            }
            t
        }
        None => {
            #[cfg(test)]
            crate::selkie_trace!("[FDI] represent_integer FAILED, e_fdi={e_fdi}");
            return None;
        }
    };

    // Step 3: M_θ via order-basis decomposition.
    let m_theta = action_matrix(&theta, order.order(), &gen_matrices, f)?;
    #[cfg(test)]
    {
        crate::selkie_trace!("CREF_FDI mat00={:?}", m_theta.entry(0, 0));
        crate::selkie_trace!("CREF_FDI mat01={:?}", m_theta.entry(0, 1));
        crate::selkie_trace!("CREF_FDI mat10={:?}", m_theta.entry(1, 0));
        crate::selkie_trace!("CREF_FDI mat11={:?}", m_theta.entry(1, 1));
    }

    // Step 3.5: Multiply M_θ entries by u⁻¹ mod 2^{e_FDI+2}.
    //
    // θ has norm u·(2^{e_FDI} − u), so the endomorphism θ/u has
    // degree 2^{e_FDI} − u, coprime to 2. The kernel of the
    // (2,2)-chain is generated by (θ/u)(basis), not θ(basis).
    // Since the action matrix is linear in θ, multiplying matrix
    // entries by u⁻¹ is equivalent to applying (θ/u) to the
    // basis. The modulus 2^{e_FDI+2} suffices because the kernel
    // lives in E[2^{e_FDI}] and the extra +2 accounts for the
    // gluing's order-4 structure.
    //
    // # Divergences
    //
    // This step is not in the spec pseudocode (Algorithm 3.15)
    // but is present in the C ref (dim2id2iso.c lines 133–143).
    // Without it, the ActionByTranslation determinant is
    // degenerate and the (2,2)-chain always fails.
    let u_scalar = u.to_scalar();
    let u_inv = u_scalar
        .inv_mod2k(e_fdi + 2)
        .expect("u is odd by IsogenyDegree invariant");
    let m00 = m_theta.entry(0, 0).mul_mod2k(&u_inv, e_fdi + 2);
    let m01 = m_theta.entry(0, 1).mul_mod2k(&u_inv, e_fdi + 2);
    let m10 = m_theta.entry(1, 0).mul_mod2k(&u_inv, e_fdi + 2);
    let m11 = m_theta.entry(1, 1).mul_mod2k(&u_inv, e_fdi + 2);

    // Step 4–5: Match the C ref's flow (dim2id2iso.c:121–160):
    //
    // 1. Double Montgomery basis from order 2^f to order 2^(e_fdi+2)
    // 2. Apply θ/u via three biladder calls at e_fdi+2 precision
    // 3. Lift both bases to Jacobian
    //
    // The C ref doubles BEFORE the biladder (line 121), then applies
    // at precision `length + HD_extra_torsion` (line 148). This is
    // critical: the scalars are mod 2^(e_fdi+2), so the basis must
    // have matching order. Using full-precision biladder on the full
    // 2^f-order basis computes the WRONG endomorphism because the
    // extra zero bits at positions e_fdi+2..f change the group
    // element (verified empirically).
    let doublings = f.value() - 2 - e_fdi;
    let mut doubled_p = basis_t.P;
    let mut doubled_q = basis_t.PmQ;
    let mut doubled_pmq = basis_t.Q;
    for _ in 0..doublings {
        doubled_p = doubled_p.double();
        doubled_q = doubled_q.double();
        doubled_pmq = doubled_pmq.double();
    }
    // Do NOT normalize the doubled basis points. The C reference's
    // biladder (`xDBLMUL`, `ec.c:384`) operates on the unnormalized
    // post-doubling basis (`tmp_bas` in `matrix_application_even_basis`,
    // `id2iso.c:103`), and the subsequent `lift_basis` (`basis.c:121`)
    // normalizes only `P.z` to 1 before calling `lift_basis_normalized`.
    // [`TorsionBasis::lift`] normalizes its `R` component internally via
    // `R.Z.invert()`, so we get the same lift behavior as C ref without
    // having to pre-normalize here. Pre-normalizing `doubled_p` would
    // make Selkie's biladder run on a different projective `(X : Z)`
    // representative than C ref, producing a `theta_q`/`theta_pmq` rep
    // that flows into the Okeya-Sakurai lift differently and ultimately
    // gives a byte-different (but projectively-equal) `K2_8.P2`.
    let doubled_basis = TorsionBasis::from_propagated(doubled_p, doubled_q, doubled_pmq);

    let endo_bits = TorsionExponent::try_from(e_fdi + 2).ok()?;
    let theta_p = doubled_basis.biscalar_mul(&m00, &m10, endo_bits);
    let theta_q = doubled_basis.biscalar_mul(&m01, &m11, endo_bits);
    let theta_pmq = doubled_basis.biscalar_mul(
        &m00.sub_mod2k(&m01, e_fdi + 2),
        &m10.sub_mod2k(&m11, e_fdi + 2),
        endo_bits,
    );

    #[cfg(test)]
    {
        let fp2_hex = |v: &crate::fields::fp2::Fp2| {
            let bytes = v.to_bytes();
            let re: String = bytes[..32]
                .iter()
                .rev()
                .map(|b| format!("{b:02x}"))
                .collect();
            let im: String = bytes[32..]
                .iter()
                .rev()
                .map(|b| format!("{b:02x}"))
                .collect();
            format!("0x{re} + i*0x{im}")
        };
        crate::selkie_trace!("THETA_BASIS_PX={}", fp2_hex(&theta_p.X));
        crate::selkie_trace!("THETA_BASIS_PZ={}", fp2_hex(&theta_p.Z));
        crate::selkie_trace!("THETA_BASIS_QX={}", fp2_hex(&theta_q.X));
        crate::selkie_trace!("THETA_BASIS_QZ={}", fp2_hex(&theta_q.Z));
        crate::selkie_trace!("THETA_BASIS_PMQX={}", fp2_hex(&theta_pmq.X));
        crate::selkie_trace!("THETA_BASIS_PMQZ={}", fp2_hex(&theta_pmq.Z));
    }

    // Lift using (P, Q) kernel generators (with PmQ as the difference
    // point), matching the C reference's `copy_bases_to_kernel`
    // (`hd.c:82-93`). The lifted Jacobian pairs `(p_jac_1, p_jac_2)`
    // and `(q_jac_1, q_jac_2)` form the (2,2)-isogeny kernel
    // generators `K1 = (P, θP)` and `K2 = (Q, θQ)` on the product
    // `E_t × E_t`.
    let comp1 = TorsionBasis::from_propagated(doubled_p, doubled_q, doubled_pmq);
    let (p_jac_1, q_jac_1) = comp1.lift(&curve_t)?;
    let comp2 = TorsionBasis::from_propagated(theta_p, theta_q, theta_pmq);
    let (p_jac_2, q_jac_2) = comp2.lift(&curve_t)?;

    // No Jacobian doubling needed — basis was doubled before biladder.
    let k1_jac = (p_jac_1, p_jac_2);
    let k2_jac = (q_jac_1, q_jac_2);

    // Step 6: (2,2)-isogeny chain on E_t × E_t.
    let product = surfaces::EllipticProduct::new(curve_t, curve_t);
    let kernel = surfaces::Kernel::from_jacobian(product, k1_jac, k2_jac);

    // Push all three basis points (P, Q, PmQ) through the chain,
    // matching the C ref (dim2id2iso.c:903-905). The outer chain
    // needs all three for `apply_scaled` — using only P and Q forces
    // `projective_difference` to recompute PmQ, giving an inconsistent
    // projective representative that breaks the Okeya-Sakurai lift.
    let zero = ProjectiveXOnlyPoint::identity(&curve_t);
    let (codomain, images) = kernel.isogeny_extra_torsion(
        TorsionExponent::try_from(e_fdi).ok()?,
        &[(basis_t.P, zero), (basis_t.PmQ, zero), (basis_t.Q, zero)],
    )?;

    let e_out = &codomain.E1;
    let p_out = images[0].0;
    let q_out = images[1].0;
    let pmq_out = images[2].0;
    if e_out.recover_y(&p_out.to_affine_x()).is_none()
        || e_out.recover_y(&q_out.to_affine_x()).is_none()
    {
        crate::selkie_trace!("[fixed_degree_isogeny] chain output invalid — retry");
        return None;
    }

    #[cfg(test)]
    crate::selkie_trace!("[fixed_degree_isogeny] chain OK, e_fdi={e_fdi}");
    Some((codomain.E1, p_out, q_out, pmq_out))
}

/// [IdealToIsogeny][Alg. 3.13] (Algorithm [3.13][Alg. 3.13]).
///
/// Given a left O₀-ideal I, computes the codomain E_I of the
/// corresponding isogeny φ_I : E₀ → E_I, and the images
/// φ_I(P₀) and φ_I(Q₀) of the torsion basis.
///
/// Internally decomposes I via [SuitableIdeals][Alg. 3.16],
/// computes two odd-degree isogenies via [FixedDegreeIsogeny][Alg. 3.15],
/// and combines them through a (2,2)-isogeny chain.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls SuitableIdeals and
/// RepresentInteger (both variable-time).
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived ideals during signing (Algorithm 4.2).
///
/// [Alg. 3.13]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
/// [Alg. 3.16]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16
impl<const N: usize> LeftIdeal<N> {
    /// Compute the isogeny corresponding to this ideal.
    ///
    /// Returns `(E_I, φ_I(P₀), φ_I(Q₀), φ_I(P₀ − Q₀))` or `None` if
    /// the decomposition or chain fails probabilistically.
    ///
    /// # Why a `PmQ` is returned
    ///
    /// Downstream consumers (`SplitAuxiliaryIsogeny`, even-response
    /// chain) form additional kernels from these basis points. The
    /// (2,2)-chain's `lift_basis` (Okeya-Sakurai y-recovery) requires
    /// a `PmQ` projective representative consistent with the chain's
    /// own evaluation history of `P` and `Q`. Recomputing
    /// `projective_difference(P, Q)` after the chain picks a sqrt
    /// branch that is not aligned with the chain's internal lift,
    /// which manifests as `count_splitting_indices = 0` at the next
    /// (2,2)-chain's terminal theta null. Pushing `PmQ` through the
    /// chain alongside `P` and `Q`, and propagating it through the
    /// final `M_{β₁}` matrix application via `biscalar_mul`, keeps
    /// every downstream kernel splittable.
    ///
    /// # Divergences
    ///
    /// The SQIsign v2.0.1 spec (Algorithm 3.13) describes
    /// `IdealToIsogeny` as returning only `(E_I, φ_I(P₀), φ_I(Q₀))`
    /// and does not specify how the projective representative of
    /// `φ_I(P₀ − Q₀)` is to be constructed for downstream consumers.
    /// The C reference threads `PmQ` through every isogeny it
    /// computes (a `theta_couple_curve_with_basis_t` always carries
    /// `B.PmQ`). Implementing the spec without that thread produces
    /// a build that fails interoperability against C-reference KAT
    /// vectors at the response phase even when every other invariant
    /// matches.
    pub fn to_isogeny<R: rand_core::RngCore>(
        self,
        rng: &mut R,
    ) -> Option<(
        Curve,
        ProjectiveXOnlyPoint,
        ProjectiveXOnlyPoint,
        ProjectiveXOnlyPoint,
    )> {
        let norm = *self.norm();
        self.to_isogeny_with_norm(&norm, rng)
    }

    /// [`to_isogeny`](Self::to_isogeny) with an explicit norm override
    /// for the post-matrix scaling factor.
    ///
    /// `to_isogeny` uses `self.norm()` for both the suitable-ideals
    /// decomposition and the post-matrix `1/(nrd(I)·d₁)` scaling.
    /// When the caller has pre-reduced the ideal (replacing `I` with
    /// `δ⁻¹ · I` to fit a width budget), `self.norm()` is the
    /// *reduced* norm — but the kernel-isotropy condition consumed
    /// downstream by `SplitAuxiliaryIsogeny` requires the *original*
    /// norm in the scaling formula. The C reference handles this
    /// implicitly: `find_uv` makes a local copy of the input and
    /// reduces it internally, so `lideal->norm` (used at the
    /// post-matrix scaling step) keeps the original value even
    /// though the enumeration uses the reduced lattice.
    ///
    /// This entry point lets the caller supply the original norm
    /// while still passing the pre-reduced ideal as `self`.
    pub fn to_isogeny_with_norm<R: rand_core::RngCore>(
        self,
        original_norm: &BigInt<N>,
        rng: &mut R,
    ) -> Option<(
        Curve,
        ProjectiveXOnlyPoint,
        ProjectiveXOnlyPoint,
        ProjectiveXOnlyPoint,
    )> {
        const { assert!(N <= 8, "to_isogeny supports N ≤ 8") };
        let f = TorsionExponent::FULL;

        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] before suitable_ideals: drbg_offset=0x{:x}",
            crate::drbg::debug::offset()
        );

        // Step 1: Decompose via SuitableIdeals.
        #[cfg(test)]
        let _t0 = std::time::Instant::now();
        let sui = self.suitable_ideals()?;
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] after suitable_ideals: drbg_offset=0x{:x} elapsed={:?}",
            crate::drbg::debug::offset(),
            _t0.elapsed()
        );

        // Cross-check dump against C ref's [KEYGEN_PROBE] in
        // `id2iso/ref/lvlx/dim2id2iso.c:846`. Same format/order so a
        // diff localizes whether `(s,t,u,v,β₁,β₂,d₁,d₂)` matches —
        // i.e., whether `reduce_to_prime_norm` produced the same
        // reduced ideal as the C ref despite same DRBG byte stream.
        #[cfg(test)]
        {
            use crate::quaternions::precomputed::EXTREMAL_ORDERS;
            let s_idx = EXTREMAL_ORDERS
                .iter()
                .position(|o| o.q() == sui.factor1.order.q())
                .map_or(-1i32, |i| i as i32);
            let t_idx = EXTREMAL_ORDERS
                .iter()
                .position(|o| o.q() == sui.factor2.order.q())
                .map_or(-1i32, |i| i as i32);
            let b1 = &*sui.factor1.beta;
            let b2 = &*sui.factor2.beta;
            crate::selkie_trace!("[KEYGEN_PROBE] s={s_idx} t={t_idx}");
            crate::selkie_trace!(
                "[KEYGEN_PROBE] beta_s coord=[{}, {}, {}, {}] denom={}",
                b1.a,
                b1.b,
                b1.c,
                b1.d,
                b1.denom
            );
            crate::selkie_trace!(
                "[KEYGEN_PROBE] beta_t coord=[{}, {}, {}, {}] denom={}",
                b2.a,
                b2.b,
                b2.c,
                b2.d,
                b2.denom
            );
            let d_s = BigInt::<4>::from(sui.factor1.degree);
            let d_t = BigInt::<4>::from(sui.factor2.degree);
            crate::selkie_trace!("[KEYGEN_PROBE] d_s={d_s} d_t={d_t}");
            crate::selkie_trace!("[KEYGEN_PROBE] u_pre_gcd={} v_pre_gcd={}", sui.u, sui.v);
            crate::selkie_trace!("[KEYGEN_PROBE] lideal_norm={}", self.norm());
        }

        // Steps 2–3: degrees (already in sui.factor1.degree, sui.factor2.degree).
        let d1 = &sui.factor1.degree;
        let _d2 = &sui.factor2.degree;

        // Step 4: E_u, φ_u(P_s), φ_u(Q_s) ← FixedDegreeIsogeny(s, u)
        #[cfg(test)]
        let _t1 = std::time::Instant::now();
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] before FDI(u): drbg_offset=0x{:x}",
            crate::drbg::debug::offset()
        );
        let u_deg = IsogenyDegree::new_odd(*sui.u.as_limbs())?;
        let (e_u, phi_u_p, phi_u_q, phi_u_pmq) =
            fixed_degree_isogeny(sui.factor1.order, &u_deg, rng)?;
        #[cfg(test)]
        {
            let fp2_hex = |v: &crate::fields::fp2::Fp2| -> String {
                let b = v.to_bytes();
                let re: String = b[..32].iter().rev().map(|x| format!("{:02x}", x)).collect();
                re
            };
            crate::selkie_trace!(
                "[FDI_OUT_U] phi_u_p.x_re=0x{}",
                fp2_hex(phi_u_p.to_affine_x().as_fp2())
            );
            crate::selkie_trace!(
                "[FDI_OUT_U] phi_u_q.x_re=0x{}",
                fp2_hex(phi_u_q.to_affine_x().as_fp2())
            );
            crate::selkie_trace!(
                "[FDI_OUT_U] phi_u_pmq.x_re=0x{}",
                fp2_hex(phi_u_pmq.to_affine_x().as_fp2())
            );
            crate::selkie_trace!(
                "[FDI_OUT_U] e_u.A_re=0x{}",
                fp2_hex(e_u.coefficient().as_fp2())
            );
        }
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] after FDI(u): drbg_offset=0x{:x} elapsed={:?}",
            crate::drbg::debug::offset(),
            _t1.elapsed()
        );

        // Step 5: E_v, φ_v(P_t), φ_v(Q_t) ← FixedDegreeIsogeny(t, v)
        #[cfg(test)]
        let _t2 = std::time::Instant::now();
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] before FDI(v): drbg_offset=0x{:x}",
            crate::drbg::debug::offset()
        );
        let v_deg = IsogenyDegree::new_odd(*sui.v.as_limbs())?;
        let (e_v, phi_v_p, phi_v_q, phi_v_pmq) =
            fixed_degree_isogeny(sui.factor2.order, &v_deg, rng)?;
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] after FDI(v): drbg_offset=0x{:x} elapsed={:?}",
            crate::drbg::debug::offset(),
            _t2.elapsed()
        );

        // Step 6: second component of the outer kernel.
        //
        // # Divergences
        //
        // The spec (Algorithm 3.13, line 6) writes
        // `(1/(nrd(I) · nrd(J_t))) · M_{β₁⁻¹ · β₂}` applied to
        // `(φ_v(P_t), φ_v(Q_t))`, paired with `[d₁] φ_u(P_s)` on the
        // first component (line 7). The C reference
        // (`dim2id2iso.c:881-1014`) instead builds
        // `θ = β₂ · conj(β₁)` as a quaternion, multiplies its coords
        // by `invmod(d₁ · nrd(connecting ideal), 2^f)`, and applies
        // it on the second component — with `φ_u(P_s)` (no `[d₁]`)
        // on the first.
        //
        // The two conventions differ at the quaternion level
        // (`conj(β₁)·β₂` vs `β₂·conj(β₁)` — quaternions do not
        // commute), in the scaling factor (spec `1/(nrd(I)²·d₁)` vs
        // C ref `1/(nrd(I)·d₁)`), and in whether `[d₁]` appears on
        // the first component. We follow the C ref because it is
        // the implementation whose signatures verify against the
        // published KAT vectors; the spec's matrix-product ordering
        // is flagged in `latex/sqisign-v2-spec-review.tex`.
        //
        // Using the identity `M_{conj(β)} ≡ adj(M_β) (mod 2^f)` —
        // both have determinant `nrd(β)`, and
        // `M_β · M_{conj(β)} = nrd(β) · I` — we assemble
        //
        //   M_θ = M_{β₂} · M_{conj(β₁)} = M_{β₂} · adj(M_{β₁}).
        //
        // For s = t = 0: `nrd(J_t) = 1` and
        // `nrd(β₁) = d₁ · nrd(parent_ideal)`, so the total scalar
        // applied to `M_θ` before acting on the basis is
        // `1 / (nrd(parent_ideal) · d₁)`.
        //
        // For `t > 0` the spec and C reference ( `dim2id2iso.c:885-889`)
        // add a factor of `nrd(J_t)` to the denominator to account
        // for the pushforward `β_2 ∈ J_t · self`: β_2 is scaled by
        // `nrd(J_t)` relative to its O_0-representative, and the
        // matrix action inherits that scale. The factor for `s` does
        // not appear — β_1 enters through `fixed_degree_isogeny(s, u)`
        // on the first component, which already handles the per-order
        // embedding. See [§3.1.7.2].
        //
        // For `t = 0`, `CONNECTING_IDEAL_NORMS[0] = 1` (J_0 is O₀
        // itself), so multiplying by it is a no-op. The gate on
        // `t_index > 0` matches C ref's `find_uv` (`dim2id2iso.c:651`)
        // skipping the extra `nrd(J_t)` factor when both sides came
        // from the special order.
        //
        // [§3.1.7.2]: https://sqisign.org/spec/sqisign-20250707.pdf#subsubsection.3.1.7.2
        let modulus = BigInt::<4>::ONE.shl(f.value());
        let s_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor1.order.q())?;
        let t_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor2.order.q())?;
        // After `suitable_ideals`'s cross-order post-processing
        // (`ideal.rs` `(j_i != 0) ? beta_i = conj(delta · beta_i)`),
        // beta_i ∈ I ⊆ O₀ regardless of which alternate order it
        // came from. Always decompose on O₀ for cross-order pairs,
        // matching C ref's `endomorphism_application_even_basis(...,
        // index_alternate_curve=0, ...)` at `dim2id2iso.c:1054, 1156`.
        // For the pure-special path (s = t = 0) decompose on O₀ too
        // — equivalent.
        let cross_order = s_index != 0 || t_index != 0;
        let gen_matrices_s = if cross_order {
            [
                ACTION_MATRICES[0][3],
                ACTION_MATRICES[0][4],
                ACTION_MATRICES[0][5],
            ]
        } else {
            [
                ACTION_MATRICES[s_index][3],
                ACTION_MATRICES[s_index][4],
                ACTION_MATRICES[s_index][5],
            ]
        };
        let gen_matrices_t = if cross_order {
            [
                ACTION_MATRICES[0][3],
                ACTION_MATRICES[0][4],
                ACTION_MATRICES[0][5],
            ]
        } else {
            [
                ACTION_MATRICES[t_index][3],
                ACTION_MATRICES[t_index][4],
                ACTION_MATRICES[t_index][5],
            ]
        };
        let order_for_decompose_s: &Lattice<4> = if cross_order {
            EXTREMAL_ORDERS[0].order()
        } else {
            sui.factor1.order.order()
        };
        let order_for_decompose_t: &Lattice<4> = if cross_order {
            EXTREMAL_ORDERS[0].order()
        } else {
            sui.factor2.order.order()
        };
        let m_beta1 = action_matrix(&sui.factor1.beta, order_for_decompose_s, &gen_matrices_s, f)?;
        let m_beta2 = action_matrix(&sui.factor2.beta, order_for_decompose_t, &gen_matrices_t, f)?;
        let m_beta1_adj = m_beta1.adjugate_mod(f.value());
        let m_prod = m_beta2.mat_mul_mod(&m_beta1_adj, f.value());

        // scale = 1 / (nrd(I) · d₁) mod 2^f (for s = t = 0).
        //
        // The spec formula uses `nrd(I)` for the caller-supplied
        // ideal, not the reduced equivalent `parent_ideal` that β
        // was enumerated from. The C reference (`dim2id2iso.c:885`,
        // `ibz_mul(&theta.denom, &theta.denom, &lideal->norm)`)
        // matches: `lideal` is the original input, not the reduced
        // copy used internally by `find_uv`. Using the reduced
        // ideal's norm here breaks whenever `nrd(parent_ideal)` is
        // even (the reduced norm is `nrd(δ)/nrd(I)` for an
        // LLL-first vector δ ∈ I, and that ratio can be even even
        // for odd-prime `nrd(I)`), which leaves
        // `invmod(parent_norm · d₁, 2^f)` undefined.
        //
        // The translation between β's reduced-ideal provenance
        // (where `nrd(β) = d · nrd(parent_ideal)`) and the
        // original-ideal scaling is absorbed by the identity
        // `parent_ideal = I · δ̄/nrd(I)` — conjugate multiplication
        // by δ in the quaternion algebra shifts `nrd(β)` by
        // `nrd(δ)/nrd(I)`, and the resulting matrix equation
        // collapses back to the spec's `1/nrd(I)` scaling modulo
        // 2^f.
        // Reduce the original norm mod 2^f; the scaling factor is
        // computed mod 2^f, so the value always fits in `BigInt<4>`
        // even when `original_norm` itself spans more limbs.
        let modulus_8: BigInt<8> = modulus.widen();
        let original_norm_mod_f_8 = original_norm.widen::<8>().ct_mod(&modulus_8);
        let parent_norm: BigInt<4> = original_norm_mod_f_8
            .narrow_to::<4>()
            .expect("nrd(I) mod 2^248 fits in BigInt<4>");
        let d1_big = BigInt::<4>::from_sign_and_limbs(0, *d1.limbs());
        let scale_denom = {
            let base = parent_norm.ct_mul(&d1_big).ct_mod(&modulus);
            if t_index > 0 {
                base.ct_mul(&CONNECTING_IDEAL_NORMS[t_index])
                    .ct_mod(&modulus)
            } else {
                base
            }
        };
        let scale_inv = scale_denom.invert_mod(&modulus)?;
        let s = Scalar::from(scale_inv);
        let fv = f.value();
        let s00 = s.mul_mod2k(m_prod.entry(0, 0), fv);
        let s01 = s.mul_mod2k(m_prod.entry(0, 1), fv);
        let s10 = s.mul_mod2k(m_prod.entry(1, 0), fv);
        let s11 = s.mul_mod2k(m_prod.entry(1, 1), fv);
        let fdi_v_basis = TorsionBasis::from_propagated(phi_v_p, phi_v_q, phi_v_pmq);
        let p_step6 = fdi_v_basis.eval_decomposition(&s00, &s10);
        let q_step6 = fdi_v_basis.eval_decomposition(&s01, &s11);
        let pmq_step6 =
            fdi_v_basis.eval_decomposition(&s00.sub_mod2k(&s01, fv), &s10.sub_mod2k(&s11, fv));

        // Steps 7–8: Build kernel points on E_u × E_v.
        //
        // # Divergences
        //
        // The spec (Algorithm 3.13, line 7) writes `[d₁] φ_u(P_s)`
        // for the first component. The C reference
        // (`dim2id2iso.c:949-951`) uses `φ_u(P_s)` directly — no
        // `[d₁]` multiplication. The two are equivalent for
        // splitting (the spec's `[d₁]` factor cancels against the
        // extra `1/d₁` implicit in the spec's second-component
        // scaling of `1/(nrd(I)²·d₁)` vs. the C ref's
        // `1/(nrd(parent)·d₁)`). We follow the C ref's convention
        // on both sides of the kernel since it is the
        // implementation whose signatures verify against the
        // published KAT vectors.
        let mut kp_first = phi_u_p;
        let mut kq_first = phi_u_q;
        let mut kpmq_first = phi_u_pmq;
        let mut kp_second = p_step6;
        let mut kq_second = q_step6;
        let mut kpmq_second = pmq_step6;

        // # Divergences
        //
        // The spec (Algorithm 3.13, between lines 8 and 9) says
        // to double the kernel "to reduce to 2^sui.e-torsion"
        // before passing it to Algorithm 8.47. The natural
        // reading -- double by `f - sui.e` -- is wrong.
        //
        // Algorithm 8.47 as described in the spec, and as
        // implemented by our [`Kernel::isogeny`], runs a chain
        // of `sui.e` 8-torsion isogenies. The chain's internal
        // penultimate and ultimate steps fold the kernel's
        // 4-torsion and 2-torsion residues into the last two
        // `(2,2)`-isogenies via the `hadamard_bool` mechanism
        // of Algorithm 8.41. This requires the kernel to enter
        // the chain with order `2^(sui.e + 2)` -- two torsion
        // bits above the kernel subgroup.
        //
        // The C reference implements two chain variants
        // (`theta_isogenies.c:1088`) keyed on `extra_torsion`.
        // With `extra_torsion = true`, the chain matches the
        // spec's uniform 8-torsion formulation and needs a
        // `2^(sui.e + 2)`-torsion kernel. With
        // `extra_torsion = false`, the chain runs 2 fewer
        // 8-torsion steps and adds dedicated 4-torsion and
        // 2-torsion steps at the tail, consuming only a
        // `2^sui.e`-torsion kernel. `dim2id2iso.c:1128` calls
        // the outer chain with `extra_torsion = false`, while
        // `dim2id2iso.c:181` (Algorithm 3.15) uses
        // `extra_torsion = true`.
        //
        // Our chain only supports the `extra_torsion = true`
        // variant, so we pad the kernel by leaving 2 extra
        // torsion bits instead of doubling down to
        // `2^sui.e` exactly. The `try_find_uv` filter
        // `v_2(gcd(u, v)) >= 2` ensures `sui.e <= f - 2`, so
        // `scale = f - sui.e - 2 >= 0` is always well-defined.
        //
        // Without this compensation the chain runs to
        // completion but produces a degenerate theta null: the
        // penultimate/ultimate steps double past identity, and
        // the splitting routine (`count_splitting_indices`)
        // sees either 0 or 10 vanishing `U_{i,j}(0)`
        // coordinates rather than the unique 1 that identifies
        // a genuine elliptic product. Downstream consumers
        // accept the malformed codomain silently, producing
        // wrong signing keys that fail only against KAT
        // vectors.
        //
        // Dispatch on `sui.e` vs `f`:
        //
        //   * `sui.e ≤ f − 2` → extra-torsion path. Pad the kernel by `f − sui.e − 2`
        //     doublings, leaving 2 spare torsion bits for the chain's
        //     penultimate/ultimate hadamard absorption. Calls [`Kernel::isogeny`] (=
        //     `isogeny_extra_torsion`).
        //
        //   * `sui.e ∈ {f − 1, f}` → no-extra-torsion path. Pad by `f − sui.e`
        //     doublings so the kernel is exactly `2^sui.e`. Calls
        //     [`Kernel::isogeny_no_extra_torsion`], which runs `sui.e − 2` main
        //     8-torsion steps then a dedicated 4-isogeny + 2-isogeny tail. Mirrors the
        //     C reference's `extra_torsion=false` mode at `dim2id2iso.c:1128`.
        // Always dispatch the outer chain to Mode B
        // (`isogeny_no_extra_torsion`), matching C ref's
        // `theta_chain_compute_and_eval_randomized(.., extra_torsion=false,
        // .)` at `dim2id2iso.c:1128`. C ref uses Mode B for the outer
        // chain regardless of available torsion; we previously
        // dispatched to Mode A when `sui.e ≤ f − 2` and got a different
        // codomain rep. With the `double_unnormalized` curve fix landed,
        // Mode B is byte-stable on FDI codomains and matches C ref.
        let no_extra_torsion = true;
        let scale = f.value().checked_sub(sui.e.value())?;
        #[cfg(test)]
        crate::selkie_trace!(
            "[to_isogeny] outer chain: sui.e={}, scale={scale}",
            sui.e.value()
        );
        // Outer-chain kernel-prep doubling, mirroring C ref's
        // `double_couple_point_iter(&ker.T1, TORSION_EVEN_POWER - exp,
        // ...)` (`dim2id2iso.c:1196-1198`). C ref calls `ec_dbl` on a
        // freshly returned `Fu_codomain` / `Fv_codomain` curve whose
        // `is_A24_computed_and_normalized` flag is `false`, so it
        // dispatches to the un-normalized `xDBL` (`ec.c:234`). To
        // produce the same `(X : Z)` byte-rep we use
        // [`ProjectiveXOnlyPoint::double_unnormalized`], which reads
        // the curve's projective `(A : C)` from `theta_to_product`
        // (preserved un-divided since the `theta_to_product` rewrite)
        // and applies the `xDBL` formula directly. Without this
        // un-normalized doubling, our `(X : Z)` drifts from C ref by
        // a `4C^scale` projective scalar; `lift_basis` absorbs the
        // drift on the P side (R normalizes to Z=1) but the
        // Okeya-Sakurai recovery on Q propagates it, breaking
        // byte-equality at the outer-chain `step=glue null` for any
        // KAT with `scale > 0`.
        for _ in 0..scale {
            kp_first = kp_first.double_unnormalized();
            kp_second = kp_second.double_unnormalized();
            kq_first = kq_first.double_unnormalized();
            kq_second = kq_second.double_unnormalized();
            kpmq_first = kpmq_first.double_unnormalized();
            kpmq_second = kpmq_second.double_unnormalized();
        }

        // Diagnostics: kernel order and curve-membership checks, plus
        // affine x-coordinates in the exact format the SQIsign C
        // reference prints (see `dim2id2iso.c:1036-1107`). Callers
        // with access to the C reference's stderr can diff the
        // `OUTER_KER` lines here against the fixture in
        // `tests/fixtures/cref_outer_ker_kat_vector_*.txt` to locate
        // which stage first diverges. The on-curve and exact-order
        // checks mirror the C reference's
        // `test_point_order_twof(..., exp)` assertions at
        // `dim2id2iso.c:1109-1110`.
        #[cfg(test)]
        {
            let on_curve =
                |c: &Curve, p: &ProjectiveXOnlyPoint| c.recover_y(&p.to_affine_x()).is_some();
            let has_order = |p: ProjectiveXOnlyPoint, e: u32| -> (bool, bool) {
                let mut q = p;
                for _ in 0..(e - 1) {
                    q = q.double();
                }
                let half = !bool::from(q.is_identity());
                q = q.double();
                (half, bool::from(q.is_identity()))
            };
            // Hex rendering matches `fp_encode` in the C reference:
            // little-endian byte array, printed high-byte first.
            let fp2_hex = |v: &crate::fields::fp2::Fp2| -> (String, String) {
                let b = v.to_bytes();
                let re: String = b[..32].iter().rev().map(|x| format!("{:02x}", x)).collect();
                let im: String = b[32..].iter().rev().map(|x| format!("{:02x}", x)).collect();
                (re, im)
            };
            let point_hex = |p: &ProjectiveXOnlyPoint| -> (String, String) {
                fp2_hex(p.to_affine_x().as_fp2())
            };
            let e = sui.e.value() + 2;

            let (p1re, p1im) = point_hex(&kp_first);
            let (p2re, p2im) = point_hex(&kp_second);
            let (q1re, q1im) = point_hex(&kq_first);
            let (q2re, q2im) = point_hex(&kq_second);
            crate::selkie_trace!("OUTER_KER T1.P1_x_re=0x{p1re} T1.P1_x_im=0x{p1im}");
            crate::selkie_trace!("OUTER_KER T1.P2_x_re=0x{p2re} T1.P2_x_im=0x{p2im}");
            crate::selkie_trace!("OUTER_KER T2.P1_x_re=0x{q1re} T2.P1_x_im=0x{q1im}");
            crate::selkie_trace!("OUTER_KER T2.P2_x_re=0x{q2re} T2.P2_x_im=0x{q2im}");
            let (e1re, _e1im) = fp2_hex(&e_u.j_invariant());
            let (e2re, _e2im) = fp2_hex(&e_v.j_invariant());
            crate::selkie_trace!("OUTER_KER E1_j_re=0x{e1re}");
            crate::selkie_trace!("OUTER_KER E2_j_re=0x{e2re}");
            let (e1a_re, e1a_im) = fp2_hex(e_u.coefficient().as_fp2());
            let (e2a_re, e2a_im) = fp2_hex(e_v.coefficient().as_fp2());
            crate::selkie_trace!("OUTER_KER E1_A_re=0x{e1a_re} E1_A_im=0x{e1a_im}");
            crate::selkie_trace!("OUTER_KER E2_A_re=0x{e2a_re} E2_A_im=0x{e2a_im}");
            crate::selkie_trace!("OUTER_KER exp={e}");

            let (kp1_half, kp1_full) = has_order(kp_first, e);
            let (kp2_half, kp2_full) = has_order(kp_second, e);
            let (kq1_half, kq1_full) = has_order(kq_first, e);
            let (kq2_half, kq2_full) = has_order(kq_second, e);
            crate::selkie_trace!(
                "[OUTER_KER] on_curve kp=({},{}) kq=({},{}) kpmq=({},{}); order 2^{e}: kp=({kp1_half},{kp1_full})/({kp2_half},{kp2_full}) kq=({kq1_half},{kq1_full})/({kq2_half},{kq2_full})",
                on_curve(&e_u, &kp_first),
                on_curve(&e_v, &kp_second),
                on_curve(&e_u, &kq_first),
                on_curve(&e_v, &kq_second),
                on_curve(&e_u, &kpmq_first),
                on_curve(&e_v, &kpmq_second),
            );
        }

        // Step 9: (2,2)-isogeny chain on E_u × E_v.
        let product = surfaces::EllipticProduct::new(e_u, e_v);
        let kernel = surfaces::Kernel::from_montgomery(
            product,
            (kp_first, kp_second),
            (kq_first, kq_second),
            (kpmq_first, kpmq_second),
        )?;

        // Chain exponent is `sui.e`. The C ref calls
        // `theta_chain_compute_and_eval_randomized(exp=sui.e, ...,
        // extra_torsion=false)` here
        // (`dim2id2iso.c:1128`) — full-length chain, no extra
        // torsion bits, kernel of order exactly 2^sui.e. The chain
        // produces a `(2^sui.e, 2^sui.e)`-isogeny of length sui.e.
        //
        // The earlier version of this call used
        // `isogeny_extra_torsion(chain_e = sui.e − 2)`, expecting
        // kernel 2^(chain_e + 2) = 2^sui.e with two spare
        // torsion bits for the internal double-and-add. That only
        // produced a `(2^(sui.e − 2), 2^(sui.e − 2))`-isogeny — four
        // bits too small — so the codomain landed at
        // `A / [2²](P, Q)` rather than `A / (P, Q)`, and the
        // splitting check at the end of the chain found zero
        // candidate indices.
        let chain_e = sui.e;
        let zero_v = ProjectiveXOnlyPoint::identity(&e_v);
        // Push `PmQ` through the chain alongside `P` and `Q`. The
        // chain's evaluator (`gluing_eval_point_special_case` →
        // `theta_isogeny_eval`) preserves the projective rep
        // semantics required by the next chain's `lift_basis`. See
        // the doc comment on this function for why we cannot recover
        // `PmQ` after the fact via `projective_difference`.
        let chain_pts = &[(phi_u_p, zero_v), (phi_u_q, zero_v), (phi_u_pmq, zero_v)];
        // The outer chain in keygen and signing must consume four bytes
        // of randomness at its splitting step to mirror the C reference's
        // `theta_chain_compute_and_eval_randomized` (`dim2id2iso.c:1261`),
        // which calls `splitting_compute(..., randomize=true)`. The four
        // bytes pick a uniform index in `[0, 6)` selecting one of six
        // `NORMALIZATION_TRANSFORMS` matrices that re-randomizes the
        // post-splitter projective representative. Without this, the
        // public output curve is a deterministic function of secret
        // kernel structure (a side-channel leak) and bytes diverge from
        // the C reference's published KAT vectors. FDI's internal chain
        // (`isogeny_extra_torsion`, called above) is the only chain
        // where C ref calls the non-randomized
        // `theta_chain_compute_and_eval`.
        //
        // The Mode A branch (else) does NOT yet match the C reference
        // bytewise: C ref always uses `extra_torsion=false` (Mode B)
        // for the outer chain regardless of available torsion. An
        // attempt to unify by routing both branches through Mode B
        // with `scale = f - sui.e` regressed the KAT pass count from
        // 35 to 33; Mode B in `isogeny_inner_no_extra_torsion`
        // appears to compute something subtly different from the
        // C reference's `_theta_chain_compute_impl(..., false, true)`
        // for the case where the kernel does NOT come from a chain
        // already short on torsion. TODO: instrument step-by-step to
        // localize the divergence.
        let (codomain, images) = if no_extra_torsion {
            kernel.isogeny_no_extra_torsion(chain_e, chain_pts, Some(rng))?
        } else {
            kernel.isogeny(chain_e, chain_pts, None)?
        };

        #[cfg(test)]
        {
            let fp2_hex = |v: &crate::fields::fp2::Fp2| -> String {
                let b = v.to_bytes();
                let re: String = b[..32].iter().rev().map(|x| format!("{:02x}", x)).collect();
                let im: String = b[32..].iter().rev().map(|x| format!("{:02x}", x)).collect();
                format!("re=0x{re} im=0x{im}")
            };
            crate::selkie_trace!(
                "[CHAIN_OUT] codomain.E1.j {}",
                fp2_hex(&codomain.E1.j_invariant())
            );
            crate::selkie_trace!(
                "[CHAIN_OUT] codomain.E2.j {}",
                fp2_hex(&codomain.E2.j_invariant())
            );
            crate::selkie_trace!(
                "[CHAIN_OUT] codomain.E1.A {}",
                fp2_hex(codomain.E1.coefficient().as_fp2())
            );
            crate::selkie_trace!(
                "[CHAIN_OUT] codomain.E2.A {}",
                fp2_hex(codomain.E2.coefficient().as_fp2())
            );
        }

        // Steps 10–13: Pick correct output curve via Weil-pairing
        // disambiguation.
        //
        // The (2,2)-chain on `E_u × E_v` splits as a product of two
        // curves; one is `E_I` (what we want), the other an auxiliary
        // unrelated to the response isogeny. Following the C reference
        // (`dim2id2iso.c:1148-1178`):
        //
        //   w_s     = e_{2^f}(canonical basis on E_s)
        //   w_chain = e_{2^f}(images on chosen codomain side)
        //   E_I = side where `w_chain == w_s^(d₁ · u² mod 2^f)`
        //
        // The exponent `d₁·u²` accounts for the composite isogeny
        // `phi_u (degree u) ∘ chain restriction (degree d₁·u)` from
        // E_s to the correct codomain side. Without this disambiguation
        // a 50/50 wrong-side selection produces a basis on the
        // auxiliary curve, and downstream `SplitAuxiliaryIsogeny`
        // reports `count_splitting_indices = 0` because its kernel is
        // malformed — not a (2,2)-isotropic subgroup of the intended
        // product.
        let s_idx_for_disamb = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor1.order.q())?;
        let s_curve_idx = precomputed::torsion_basis::ExtremalCurve::try_from(s_idx_for_disamb)
            .expect("EXTREMAL_ORDERS length matches ExtremalCurve::ALL by compile-time assert");
        let (s_px, s_qx, s_pmq_x, s_a_coeff) = s_curve_idx.basis();
        let s_curve = if s_curve_idx == precomputed::torsion_basis::ExtremalCurve::E0 {
            Curve::E0
        } else {
            Curve::from(crate::curves::montgomery::Coefficient::from(s_a_coeff))
        };
        let s_p = ProjectiveXOnlyPoint::from_affine_x(s_px, &s_curve);
        let s_q = ProjectiveXOnlyPoint::from_affine_x(s_qx, &s_curve);
        let s_pmq = ProjectiveXOnlyPoint::from_affine_x(s_pmq_x, &s_curve);
        // Tate-based Weil pairing expects P+Q as third arg; compute
        // it via differential addition from (P, Q, P-Q).
        let s_ppq = s_p.differential_add(&s_q, &s_pmq);
        let w_s = crate::curves::pairing::weil_pairing(&s_p, &s_q, &s_ppq, f);

        // Expected: w_s^(d₁ · u² mod 2^f).
        let d1_big = BigInt::<4>::from_sign_and_limbs(0, *d1.limbs());
        let u_sq = sui.u.ct_mul(&sui.u);
        let exp_disamb = d1_big.ct_mul(&u_sq).ct_mod(&modulus);
        let expected = w_s.pow_scalar(&Scalar::from(exp_disamb));

        // Compute Weil pairing on codomain.E1 side using propagated
        // PmQ; convert to P+Q via differential addition.
        let ppq_e1 = images[0].0.differential_add(&images[1].0, &images[2].0);
        let w1 = crate::curves::pairing::weil_pairing(&images[0].0, &images[1].0, &ppq_e1, f);

        let matched_e1 = w1 == expected;
        #[cfg(test)]
        {
            // Cross-check with E2 side too — exactly one should match
            // if disambiguation is sound.
            let ppq_e2 = images[0].1.differential_add(&images[1].1, &images[2].1);
            let w2 = crate::curves::pairing::weil_pairing(&images[0].1, &images[1].1, &ppq_e2, f);
            let matched_e2 = w2 == expected;
            crate::selkie_trace!(
                "[to_isogeny] disamb: E1 match={matched_e1}, E2 match={matched_e2}"
            );
        }
        let (e_i, p_chain, q_chain, pmq_chain) = if matched_e1 {
            (codomain.E1, images[0].0, images[1].0, images[2].0)
        } else {
            (codomain.E2, images[0].1, images[1].1, images[2].1)
        };

        // Step 14: [P_I, Q_I]^T ← (1/(u·d₁)) M_{β₁} [P_I, Q_I]^T
        let s_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor1.order.q())?;
        let gen_matrices_s = [
            ACTION_MATRICES[s_index][3],
            ACTION_MATRICES[s_index][4],
            ACTION_MATRICES[s_index][5],
        ];
        let m_beta1 = action_matrix(
            &sui.factor1.beta,
            sui.factor1.order.order(),
            &gen_matrices_s,
            f,
        )?;

        // scalar = 1/(u · d₁) mod 2^f
        let ud1 = sui
            .u
            .ct_mul(&BigInt::<4>::from_sign_and_limbs(0, *d1.limbs()));
        let ud1_inv = ud1.invert_mod(&modulus)?;

        // Apply `(1/(u·d₁)) M_{β₁}` to the basis `(P, Q, PmQ)` using
        // biscalar multiplication for all three points so the
        // resulting `PmQ` is a propagated projective rep — never the
        // sqrt-branch result of `projective_difference(P', Q')`.
        //
        // # Mathematical invariant (verified)
        //
        // The output basis `(P_I, Q_I, PmQ_I)` satisfies
        //   `e_{2^f}(P_I, Q_I) = e_{2^f}(canonical basis on E_s)^nrd(self)`
        // where `self` is the input ideal. Derivation:
        //   chain Weil = e_E_s^(d₁·u²)  (from disambiguation step)
        //   M_{β₁} det ≡ nrd(β₁) = d₁·nrd(self) mod 2^f
        //   scaling by 1/(u·d₁) multiplies det by 1/(u·d₁)²
        //   final det = nrd(self)/(u²·d₁)
        //   total Weil = e_E_s^(d₁·u² · nrd(self)/(u²·d₁)) = e_E_s^nrd(self)
        //
        // This invariant matters for downstream `SplitAuxiliaryIsogeny`:
        // the response-phase kernel's isotropy condition
        // `e_E_com · q⁻² · e_E_aux' = 1` only holds when
        // `nrd(I_inter) = q · nrd(I_com) · nrd(I_aux)` literally —
        // i.e., when `self` here is the input ideal's *original* norm,
        // not a reduced equivalent.
        let chain_basis = TorsionBasis::from_propagated(p_chain, q_chain, pmq_chain);
        let (p_i, q_i, pmq_i) = m_beta1.apply_scaled_basis(&ud1_inv, &chain_basis, f);

        Some((e_i, p_i, q_i, pmq_i))
    }
}

// TODO: Complete KernelDecomposedToIdeal (Algorithm 3.17, partially
// implemented above as kernel_to_ideal).

#[cfg(test)]
mod tests;
