//! The Deuring correspondence: converting between ideals and isogenies.
//!
//! This module bridges the quaternion algebra world ([`crate::quaternions`])
//! and the elliptic curve world ([`crate::curves`], [`crate::surfaces`]).
//! The Deuring correspondence establishes a bijection between left ideals
//! of a maximal order O ⊂ B_{p,∞} and separable isogenies from E where
//! End(E) ≅ O.
//!
//! The main algorithms are:
//! - [`IdealToIsogeny`][Alg. 3.13] (Algorithm 3.13): convert an O₀-ideal to an
//!   isogeny and its images on torsion points
//! - [`FixedDegreeIsogeny`][Alg. 3.15] (Algorithm 3.15): compute an isogeny of
//!   prescribed degree from precomputed data
//! - [`SuitableIdeals`][Alg. 3.16] (Algorithm 3.16): decompose an ideal into
//!   pieces with coprime odd norms
//!
//! See [§3.2] of the SQIsign specification.
//!
//! [§3.2]: https://sqisign.org/spec/sqisign-20250707.pdf#section.3.2
//! [Alg. 3.13]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
//! [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
//! [Alg. 3.16]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16

pub(crate) mod endomorphism;
pub(crate) mod precomputed;

use endomorphism::ActionMatrix;
use precomputed::ACTION_MATRICES;

use crate::{
    curves::{
        TorsionBasis, TorsionExponent,
        isogeny::{IsogenyDegree, Kernel as CurveKernel},
        montgomery::{Curve, ProjectiveXOnlyPoint},
        scalar::Scalar,
    },
    params::QUAT_REPRES_BOUND_INPUT,
    quaternions::{
        algebra::Element,
        bigint::BigInt,
        lattice::{ExtremalOrder, Lattice, LeftIdeal},
        precomputed::EXTREMAL_ORDERS,
    },
    surfaces,
};

/// A kernel generator decomposed in a torsion basis (P, Q).
///
/// Represents the point [a]P + [b]Q where a, b are scalars. The
/// actual curve point is computed by evaluating the scalars against
/// a specific torsion basis.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KernelDecomposition {
    /// Coefficient of P.
    pub a: Scalar,
    /// Coefficient of Q.
    pub b: Scalar,
}

/// Extension trait for computing endomorphism action matrices
/// from quaternion elements already expressed in the order basis.
///
/// Given an element with coordinates (c₀, c₁, c₂, c₃) in the order
/// basis, computes M_α = c₀·M₁ + c₁·M₂ + c₂·M₃ + c₃·M₄ (mod 2^f).
///
/// See §3.2.1.1 of the spec.
pub trait DeuringAction {
    /// Compute the action matrix given four order-basis action matrices.
    ///
    /// The element's (a, b, c, d) coordinates are used as coefficients.
    /// The caller must ensure the element is expressed in the order basis,
    /// not the {1, i, j, k} basis.
    fn action_matrix(&self, basis_matrices: &[ActionMatrix; 4], f: TorsionExponent)
    -> ActionMatrix;
}

impl DeuringAction for Element<4> {
    fn action_matrix(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        f: TorsionExponent,
    ) -> ActionMatrix {
        let coords = [
            *self.a.as_bigint(),
            *self.b.as_bigint(),
            *self.c.as_bigint(),
            *self.d.as_bigint(),
        ];
        let mut result = ActionMatrix::ZERO;
        for i in 0..4 {
            result = result.add_scaled_mod(&coords[i], &basis_matrices[i], f.value());
        }
        result
    }
}

/// Extension trait for converting an ideal to a kernel generator
/// via the Deuring correspondence.
///
/// See [Alg. 3.14] from the spec.
///
/// [Alg. 3.14]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.14
pub trait IdealKernel {
    /// Compute the kernel decomposition for this ideal of norm 2^e.
    ///
    /// Returns scalars (a, b) such that ker φ_I is generated by
    /// [a·2^{f-e}]P₀ + [b·2^{f-e}]Q₀, where (P₀, Q₀) is the
    /// precomputed torsion basis of E₀[2^f].
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition>;
}

impl IdealKernel for LeftIdeal<4> {
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition> {
        // Step 1: Find α ∈ O₀ such that I = O₀⟨α, 2^e⟩.
        let alpha = self.generator()?;

        // Step 2: Compute M_α mod 2^e.
        let m_alpha = alpha.action_matrix(basis_matrices, e);

        // Step 3: Find [a, b]^T in the right kernel of M_α mod 2^e.
        // For a 2×2 matrix, the kernel is spanned by (-m01, m00)^T.
        let modulus = BigInt::<4>::ONE.shl(e.value());

        // Try first row: kernel direction = (-m01, m00).
        let a_big = BigInt::<4>::from(*m_alpha.entry(0, 1))
            .wrapping_neg()
            .ct_mod(&modulus);
        let b_big = BigInt::<4>::from(*m_alpha.entry(0, 0)).ct_mod(&modulus);

        let (check0, check1) = m_alpha.eval_mod(&a_big, &b_big, e.value());
        if bool::from(check0.is_zero()) && bool::from(check1.is_zero()) {
            return Some(KernelDecomposition {
                a: Scalar::from(a_big),
                b: Scalar::from(b_big),
            });
        }

        // If first row was zero, try second row.
        let a_big = BigInt::<4>::from(*m_alpha.entry(1, 1))
            .wrapping_neg()
            .ct_mod(&modulus);
        let b_big = BigInt::<4>::from(*m_alpha.entry(1, 0)).ct_mod(&modulus);

        let (check0, check1) = m_alpha.eval_mod(&a_big, &b_big, e.value());
        if bool::from(check0.is_zero()) && bool::from(check1.is_zero()) {
            return Some(KernelDecomposition {
                a: Scalar::from(a_big),
                b: Scalar::from(b_big),
            });
        }

        None
    }
}

// KernelToIdeal (Algorithm 3.17) is TorsionBasis::kernel_to_ideal() in
// curves/mod.rs.

/// Compute the even (non-backtracking) response isogeny.
///
/// Given curve E_chl with torsion basis (P, Q), quaternion α,
/// and integers e' (= e'_rsp) and r (= r_rsp), computes the
/// even response isogeny φ^even_rsp : E_chl → E.
///
/// Returns the codomain curve E and the images P', Q' of the
/// basis points.
///
/// Implements [ComputeEvenNonBacktrackingResponse][Alg. 4.6].
///
/// [Alg. 4.6]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.4.6
pub fn compute_even_response(
    _curve: &Curve,
    P: &ProjectiveXOnlyPoint,
    Q: &ProjectiveXOnlyPoint,
    alpha: &Element<4>,
    e_prime: TorsionExponent,
    r_rsp: TorsionExponent,
) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
    let e_prime = e_prime.value();
    let r_rsp = r_rsp.value();

    // Step 1: I = O₀·α + O₀·(2^r)
    let norm = BigInt::<4>::ONE.shl(r_rsp);
    let ideal = LeftIdeal::new(alpha, &norm, EXTREMAL_ORDERS[0].order());

    // Step 2: (s, t) ← IdealToKernel(I)
    let basis_mats = [
        ACTION_MATRICES[0][3], // gen2
        ACTION_MATRICES[0][4], // gen3
        ACTION_MATRICES[0][5], // gen4
        ACTION_MATRICES[0][0], // i (for the kernel computation)
    ];
    let decomp = ideal.to_kernel(&basis_mats, TorsionExponent::try_from(r_rsp).ok()?)?;

    // Step 3: K = [2^(e'+2) · s]P + [2^(e'+2) · t]Q
    let shift = e_prime + 2;
    let s_shifted = Scalar::from_limbs(*decomp.a.as_limbs()).mul_mod2k(
        &Scalar::from_limbs(*BigInt::<4>::ONE.shl(shift).as_limbs()),
        256,
    );
    let t_shifted = Scalar::from_limbs(*decomp.b.as_limbs()).mul_mod2k(
        &Scalar::from_limbs(*BigInt::<4>::ONE.shl(shift).as_limbs()),
        256,
    );

    // Compute K = [s_shifted]P + [t_shifted]Q using the biladder.
    // Need PmQ for the three-point ladder.
    let PmQ = P.projective_difference(Q);
    let basis = TorsionBasis::from_propagated(*P, *Q, PmQ);
    // TODO: PmQ from projective_difference may pick wrong branch.
    // In signing, the basis (P, Q, P-Q) should have been propagated
    // from a prior computation, not recomputed here.
    let K = basis.biscalar_mul(
        &s_shifted,
        &t_shifted,
        TorsionExponent::try_from(r_rsp + shift).ok()?,
    );

    // Step 4: E', {P', Q'} ← TwoisogenyChainSmall(K, E, r, {P, Q}, true)
    let (new_curve, images) = CurveKernel::new(K)
        .isogeny_small(TorsionExponent::try_from(r_rsp).ok()?, &[*P, *Q], true)
        .ok()?;

    Some((new_curve, images[0], images[1]))
}

// ---------------------------------------------------------------------------
// CurveWithEndomorphismRing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// IdealToIsogeny (Algorithm 3.13) + FixedDegreeIsogeny (Algorithm 3.15)
// ---------------------------------------------------------------------------

/// Compute the action matrix M_α for an element α on E_t[2^f],
/// given the order's lattice and generator action matrices.
///
/// Decomposes α from {1,i,j,k} into the order's column basis
/// (c₀, c₁, c₂, c₃), then assembles:
///
/// M_α = c₀ · I + c₁ · M_{gen2} + c₂ · M_{gen3} + c₃ · M_{gen4}  (mod 2^f)
fn action_matrix(
    elem: &Element<4>,
    order: &Lattice<4>,
    gen_matrices: &[ActionMatrix; 3],
    f: TorsionExponent,
) -> Option<ActionMatrix> {
    let coords = order.decompose(elem)?;

    // Reduce all coefficients mod 2^f. For negative coefficients,
    // ct_mod returns a negative remainder (truncated division), so
    // add the modulus to get the canonical representative in [0, 2^f).
    let modulus = BigInt::<4>::ONE.shl(f.value());
    let reduce = |c: &BigInt<4>| -> Scalar {
        let r = c.ct_mod(&modulus);
        if bool::from(r.is_negative()) {
            Scalar::from(r.ct_add(&modulus))
        } else {
            Scalar::from(r)
        }
    };

    let c0_scalar = reduce(&coords[0]);
    let mut result = ActionMatrix::new(c0_scalar, Scalar::ZERO, Scalar::ZERO, c0_scalar);

    for k in 0..3 {
        let s = reduce(&coords[k + 1]);
        let other = &gen_matrices[k];
        let fv = f.value();
        result = ActionMatrix::new(
            result
                .entry(0, 0)
                .add_mod2k(&s.mul_mod2k(other.entry(0, 0), fv), fv),
            result
                .entry(0, 1)
                .add_mod2k(&s.mul_mod2k(other.entry(0, 1), fv), fv),
            result
                .entry(1, 0)
                .add_mod2k(&s.mul_mod2k(other.entry(1, 0), fv), fv),
            result
                .entry(1, 1)
                .add_mod2k(&s.mul_mod2k(other.entry(1, 1), fv), fv),
        );
    }

    Some(result)
}

/// Compute a u-isogeny from E_t via a (2,2)-isogeny chain.
///
/// [FixedDegreeIsogeny][Alg. 3.15] (Algorithm [3.15][Alg. 3.15]):
/// given a positive odd [`IsogenyDegree`] u < 2^{f−2} and the
/// precomputed data for curve E_t, finds an endomorphism θ of E_t
/// with nrd(θ) = u·(2^{e_FDI} − u), then computes a
/// (2^{e_FDI}, 2^{e_FDI})-isogeny on E_t × E_t whose projection
/// gives the u-isogeny φ: E_t → E.
///
/// Returns `(E, φ(P_t), φ(Q_t))`.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls RepresentInteger (variable-time
/// search) and the (2,2)-chain length depends on e_FDI.
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived (u, t) values during signing (Algorithm 4.2 via
/// IdealToIsogeny).
///
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
fn fixed_degree_isogeny(
    order: &'static ExtremalOrder<4>,
    u: &IsogenyDegree,
) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
    let f = TorsionExponent::FULL;
    let p_bits = 251u32; // ⌈log₂(p)⌉ for NIST-I

    // Look up the precomputed curve and torsion basis for this order.
    let t = EXTREMAL_ORDERS.iter().position(|o| o.q() == order.q())?;

    let (px, qx, a_coeff) = precomputed::torsion_basis::basis_for_curve(t)?;
    #[cfg(test)]
    eprintln!("[FDI] t={t}, e_fdi will be computed next");
    let curve_t = if t == 0 {
        Curve::E0
    } else {
        Curve::from(crate::curves::montgomery::Coefficient::from(a_coeff))
    };
    let p_t = ProjectiveXOnlyPoint::from_affine_x(px, &curve_t);
    let q_t = ProjectiveXOnlyPoint::from_affine_x(qx, &curve_t);
    // Use precomputed PmQ where available. The biladder's three-point
    // ladder requires a PmQ whose projective representative is
    // consistent with the precomputed action matrices. Computing PmQ
    // via `projective_difference` gives a different representative
    // that causes the Okeya-Sakurai lift to recover the wrong y-sign.
    let basis_t = if t == 0 {
        let pmq_t = ProjectiveXOnlyPoint::from_affine_x(crate::params::BASIS_E0_PMQ_X, &curve_t);
        TorsionBasis::from_propagated(p_t, q_t, pmq_t)
    } else {
        // TODO: precompute PmQ for all 7 curves.
        TorsionBasis::from((p_t, q_t))
    };
    let gen_matrices = [
        ACTION_MATRICES[t][3],
        ACTION_MATRICES[t][4],
        ACTION_MATRICES[t][5],
    ];

    // Step 1: e_FDI = min(f − 2, ⌈log₂(p)⌉ − ⌈log₂(u)⌉ + QUAT_repres_bound_input)
    let e_fdi = core::cmp::min(
        f.value() - 2,
        p_bits.saturating_sub(u.bit_length()) + QUAT_REPRES_BOUND_INPUT,
    );

    // Step 2: θ ← RepresentInteger(u·(2^{e_FDI} − u), O_t, true)
    let u_wide = u.to_bigint_wide();
    let two_e_fdi = BigInt::<8>::ONE.shl(e_fdi);
    // If u ≥ 2^{e_FDI}, the product is non-positive — no solution.
    if u_wide >= two_e_fdi {
        return None;
    }
    let m = u_wide.ct_mul(&two_e_fdi.ct_sub(&u_wide));
    let order_wide = ExtremalOrder::<8>::from(*order);
    let theta = match order_wide.represent_integer(&m, true) {
        Some(t) => {
            #[cfg(test)]
            eprintln!("[FDI] represent_integer OK, e_fdi={e_fdi}");
            t
        }
        None => {
            #[cfg(test)]
            eprintln!("[FDI] represent_integer FAILED, e_fdi={e_fdi}");
            return None;
        }
    };

    // Step 3: M_θ via order-basis decomposition.
    let m_theta = action_matrix(&theta, order.order(), &gen_matrices, f)?;

    // Step 3.5: Multiply M_θ entries by u⁻¹ mod 2^{e_FDI+2}.
    //
    // θ has norm u·(2^{e_FDI} − u), so the endomorphism θ/u has
    // degree 2^{e_FDI} − u, coprime to 2. The kernel of the
    // (2,2)-chain is generated by (θ/u)(basis), not θ(basis).
    // Since the action matrix is linear in θ, multiplying matrix
    // entries by u⁻¹ is equivalent to applying (θ/u) to the
    // basis. The modulus 2^{e_FDI+2} suffices because the kernel
    // lives in E[2^{e_FDI}] and the extra +2 accounts for the
    // gluing's order-4 structure.
    //
    // # Divergences
    //
    // This step is not in the spec pseudocode (Algorithm 3.15)
    // but is present in the C ref (dim2id2iso.c lines 133–143).
    // Without it, the ActionByTranslation determinant is
    // degenerate and the (2,2)-chain always fails.
    let u_scalar = u.to_scalar();
    let u_inv = u_scalar
        .inv_mod2k(e_fdi + 2)
        .expect("u is odd by IsogenyDegree invariant");
    let m00 = m_theta.entry(0, 0).mul_mod2k(&u_inv, e_fdi + 2);
    let m01 = m_theta.entry(0, 1).mul_mod2k(&u_inv, e_fdi + 2);
    let m10 = m_theta.entry(1, 0).mul_mod2k(&u_inv, e_fdi + 2);
    let m11 = m_theta.entry(1, 1).mul_mod2k(&u_inv, e_fdi + 2);

    // Step 4–5: Match the C ref's flow (dim2id2iso.c:121–160):
    //
    // 1. Double Montgomery basis from order 2^f to order 2^(e_fdi+2)
    // 2. Apply θ/u via three biladder calls at e_fdi+2 precision
    // 3. Lift both bases to Jacobian
    //
    // The C ref doubles BEFORE the biladder (line 121), then applies
    // at precision `length + HD_extra_torsion` (line 148). This is
    // critical: the scalars are mod 2^(e_fdi+2), so the basis must
    // have matching order. Using full-precision biladder on the full
    // 2^f-order basis computes the WRONG endomorphism because the
    // extra zero bits at positions e_fdi+2..f change the group
    // element (verified empirically).
    let doublings = f.value() - 2 - e_fdi;
    let mut doubled_p = basis_t.R;
    let mut doubled_q = basis_t.S;
    let mut doubled_pmq = basis_t.RS;
    for _ in 0..doublings {
        doubled_p = doubled_p.double();
        doubled_q = doubled_q.double();
        doubled_pmq = doubled_pmq.double();
    }
    // Normalize to affine (Z=1) before the biladder. The C ref's
    // `lift_basis` normalizes P.z to 1, and the biladder's output
    // projective representative depends on the input's (X:Z). Without
    // normalization, our doubling formula produces different (X:Z)
    // than the C ref, which flows through the biladder and Okeya-Sakurai
    // lift to give wrong y-coordinates.
    let doubled_p =
        ProjectiveXOnlyPoint::from_affine_x(*doubled_p.to_affine_x().as_fp2(), &curve_t);
    let doubled_q =
        ProjectiveXOnlyPoint::from_affine_x(*doubled_q.to_affine_x().as_fp2(), &curve_t);
    let doubled_pmq =
        ProjectiveXOnlyPoint::from_affine_x(*doubled_pmq.to_affine_x().as_fp2(), &curve_t);
    let doubled_basis = TorsionBasis::from_propagated(doubled_p, doubled_q, doubled_pmq);

    let endo_bits = TorsionExponent::try_from(e_fdi + 2).ok()?;
    let theta_p = doubled_basis.biscalar_mul(&m00, &m10, endo_bits);
    let theta_q = doubled_basis.biscalar_mul(&m01, &m11, endo_bits);
    let theta_pmq = doubled_basis.biscalar_mul(
        &m00.sub_mod2k(&m01, e_fdi + 2),
        &m10.sub_mod2k(&m11, e_fdi + 2),
        endo_bits,
    );

    // Lift using (P, P-Q) kernel generators.
    let comp1 = TorsionBasis::from_propagated(doubled_p, doubled_pmq, doubled_q);
    let (p_jac_1, pmq_jac_1) = comp1.lift(&curve_t)?;
    let comp2 = TorsionBasis::from_propagated(theta_p, theta_pmq, theta_q);
    let (p_jac_2, pmq_jac_2) = match comp2.lift(&curve_t) {
        Some(r) => {
            #[cfg(test)]
            eprintln!("[FDI] comp2 lift OK, proceeding to chain");
            r
        }
        None => {
            #[cfg(test)]
            eprintln!("[FDI] comp2 lift FAILED (theta_p not on curve?)");
            return None;
        }
    };

    // No Jacobian doubling needed — basis was doubled before biladder.
    let k1_jac = (p_jac_1, p_jac_2);
    let k2_jac = (pmq_jac_1, pmq_jac_2);

    // Step 6: (2,2)-isogeny chain on E_t × E_t.
    let product = surfaces::EllipticProduct::new(curve_t, curve_t);
    let kernel = surfaces::Kernel::from_jacobian(product, k1_jac, k2_jac);

    // Push all three basis points (P, Q, PmQ) through the chain,
    // matching the C ref (dim2id2iso.c:903-905). The outer chain
    // needs all three for `apply_scaled` — using only P and Q forces
    // `projective_difference` to recompute PmQ, giving an inconsistent
    // projective representative that breaks the Okeya-Sakurai lift.
    let zero = ProjectiveXOnlyPoint::identity(&curve_t);
    let (codomain, images) = kernel.isogeny_extra_torsion(
        TorsionExponent::try_from(e_fdi).ok()?,
        &[(basis_t.R, zero), (basis_t.S, zero), (basis_t.RS, zero)],
    );

    let e_out = &codomain.E1;
    let p_out = images[0].0;
    let q_out = images[1].0;
    let pmq_out = images[2].0;
    if e_out.recover_y(&p_out.to_affine_x()).is_none()
        || e_out.recover_y(&q_out.to_affine_x()).is_none()
    {
        eprintln!("[fixed_degree_isogeny] chain output invalid — retry");
        return None;
    }

    #[cfg(test)]
    eprintln!("[fixed_degree_isogeny] chain OK, e_fdi={e_fdi}");
    Some((codomain.E1, p_out, q_out, pmq_out))
}

/// [IdealToIsogeny][Alg. 3.13] (Algorithm [3.13][Alg. 3.13]).
///
/// Given a left O₀-ideal I, computes the codomain E_I of the
/// corresponding isogeny φ_I : E₀ → E_I, and the images
/// φ_I(P₀) and φ_I(Q₀) of the torsion basis.
///
/// Internally decomposes I via [SuitableIdeals][Alg. 3.16],
/// computes two odd-degree isogenies via [FixedDegreeIsogeny][Alg. 3.15],
/// and combines them through a (2,2)-isogeny chain.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls SuitableIdeals and
/// RepresentInteger (both variable-time).
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived ideals during signing (Algorithm 4.2).
///
/// [Alg. 3.13]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
/// [Alg. 3.16]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16
impl LeftIdeal<4> {
    /// Compute the isogeny corresponding to this ideal.
    ///
    /// Returns `(E_I, φ_I(P₀), φ_I(Q₀))` or `None` if the
    /// decomposition or chain fails probabilistically.
    pub fn to_isogeny(self) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
        let f = TorsionExponent::FULL;

        // Step 1: Decompose via SuitableIdeals.
        #[cfg(test)]
        let _t0 = std::time::Instant::now();
        let sui = self.suitable_ideals()?;
        #[cfg(test)]
        eprintln!("[to_isogeny] suitable_ideals: {:?}", _t0.elapsed());

        // Steps 2–3: degrees (already in sui.factor1.degree, sui.factor2.degree).
        let d1 = &sui.factor1.degree;
        let _d2 = &sui.factor2.degree;

        // Step 4: E_u, φ_u(P_s), φ_u(Q_s) ← FixedDegreeIsogeny(s, u)
        #[cfg(test)]
        let _t1 = std::time::Instant::now();
        let u_deg = IsogenyDegree::new_odd(*sui.u.as_limbs())?;
        let (e_u, phi_u_p, phi_u_q, _phi_u_pmq) =
            fixed_degree_isogeny(sui.factor1.order, &u_deg)?;
        #[cfg(test)]
        eprintln!("[to_isogeny] FDI(u): {:?}", _t1.elapsed());

        // Step 5: E_v, φ_v(P_t), φ_v(Q_t) ← FixedDegreeIsogeny(t, v)
        #[cfg(test)]
        let _t2 = std::time::Instant::now();
        let v_deg = IsogenyDegree::new_odd(*sui.v.as_limbs())?;
        let (e_v, phi_v_p, phi_v_q, phi_v_pmq) =
            fixed_degree_isogeny(sui.factor2.order, &v_deg)?;
        #[cfg(test)]
        eprintln!("[to_isogeny] FDI(v): {:?}", _t2.elapsed());

        // Step 6: [P, Q]^T ← (1/(nrd(I)·nrd(J_t))) M_{β₂} [φ_v(P_t), φ_v(Q_t)]^T
        //
        // For t=0, nrd(J_0) = 1, so the scalar is 1/nrd(I) mod 2^f.
        // TODO: For t > 0, multiply by 1/nrd(J_t) as well.
        let modulus = BigInt::<4>::ONE.shl(f.value());
        let norm_inv = self.norm().invert_mod(&modulus)?;

        // Look up generator action matrices for order O_t.
        let t_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor2.order.q())?;
        let gen_matrices_t = [
            ACTION_MATRICES[t_index][3],
            ACTION_MATRICES[t_index][4],
            ACTION_MATRICES[t_index][5],
        ];
        let m_beta2 = action_matrix(
            &sui.factor2.beta,
            sui.factor2.order.order(),
            &gen_matrices_t,
            f,
        )?;
        // Apply scaled M_β₂ to the propagated basis (P, Q, PmQ) from FDI(v).
        // Using the propagated PmQ avoids projective_difference, which
        // gives inconsistent representatives for Okeya-Sakurai.
        let s = Scalar::from(norm_inv);
        let fv = f.value();
        let s00 = s.mul_mod2k(m_beta2.entry(0, 0), fv);
        let s01 = s.mul_mod2k(m_beta2.entry(0, 1), fv);
        let s10 = s.mul_mod2k(m_beta2.entry(1, 0), fv);
        let s11 = s.mul_mod2k(m_beta2.entry(1, 1), fv);
        let fdi_v_basis = TorsionBasis::from_propagated(phi_v_p, phi_v_q, phi_v_pmq);
        let p_step6 = fdi_v_basis.eval_decomposition(&s00, &s10);
        let q_step6 = fdi_v_basis.eval_decomposition(&s01, &s11);
        let pmq_step6 = fdi_v_basis.eval_decomposition(
            &s00.sub_mod2k(&s01, fv),
            &s10.sub_mod2k(&s11, fv),
        );

        // Steps 7–8: Build kernel points on E_u × E_v.
        let d1_scalar = d1.to_scalar();
        let mut kp_first = &d1_scalar * &phi_u_p;
        let mut kq_first = &d1_scalar * &phi_u_q;
        let mut kpmq_first = &d1_scalar * &_phi_u_pmq;
        let mut kp_second = p_step6;
        let mut kq_second = q_step6;
        let mut kpmq_second = pmq_step6;

        // Double kernel points by f − e to reduce from order 2^f to 2^e.
        // The chain exponent is e − 2 (not e), because the chain consumes
        // e−2+2 = e torsion levels (the gluing adds 2). The C ref doubles
        // by `TORSION_EVEN_POWER − exp` (dim2id2iso.c:1030).
        let scale = f.value() - sui.e.value();
        #[cfg(test)]
        eprintln!("[to_isogeny] outer chain: sui.e={}, scale={scale}", sui.e.value());
        for _ in 0..scale {
            kp_first = kp_first.double();
            kp_second = kp_second.double();
            kq_first = kq_first.double();
            kq_second = kq_second.double();
            kpmq_first = kpmq_first.double();
            kpmq_second = kpmq_second.double();
        }

        // Step 9: (2,2)-isogeny chain on E_u × E_v.
        let product = surfaces::EllipticProduct::new(e_u, e_v);
        let kernel = surfaces::Kernel::from_montgomery(
            product,
            (kp_first, kp_second),
            (kq_first, kq_second),
            (kpmq_first, kpmq_second),
        )?;

        // Chain exponent is e − 2: the chain consumes (e−2)+2 = e
        // torsion levels, matching the kernel order 2^e.
        let chain_e = TorsionExponent::try_from(sui.e.value() - 2).ok()?;
        let zero_v = ProjectiveXOnlyPoint::identity(&e_v);
        let (codomain, images) =
            kernel.isogeny_extra_torsion(chain_e, &[(phi_u_p, zero_v), (phi_u_q, zero_v)]);

        // Steps 10–13: Pick correct output curve.
        // Per Algorithm 8.47 remark, E is always correct when using
        // Isogeny22ChainWithTorsion. Skip pairing check.
        let e_i = codomain.E1;
        let (p_chain, q_chain) = (images[0].0, images[1].0);

        // Step 14: [P_I, Q_I]^T ← (1/(u·d₁)) M_{β₁} [P_I, Q_I]^T
        let s_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor1.order.q())?;
        let gen_matrices_s = [
            ACTION_MATRICES[s_index][3],
            ACTION_MATRICES[s_index][4],
            ACTION_MATRICES[s_index][5],
        ];
        let m_beta1 = action_matrix(
            &sui.factor1.beta,
            sui.factor1.order.order(),
            &gen_matrices_s,
            f,
        )?;

        // scalar = 1/(u · d₁) mod 2^f
        let ud1 = sui
            .u
            .ct_mul(&BigInt::<4>::from_sign_and_limbs(0, *d1.limbs()));
        let ud1_inv = ud1.invert_mod(&modulus)?;

        let (p_i, q_i) = m_beta1.apply_scaled(&ud1_inv, p_chain, q_chain, f);

        Some((e_i, p_i, q_i))
    }
}

// TODO: Complete KernelDecomposedToIdeal (Algorithm 3.17, partially
// implemented above as kernel_to_ideal).

#[cfg(test)]
mod tests;
