//! The Deuring correspondence: converting between ideals and isogenies.
//!
//! This module bridges the quaternion algebra world ([`crate::quaternions`])
//! and the elliptic curve world ([`crate::curves`], [`crate::surfaces`]).
//! The Deuring correspondence establishes a bijection between left ideals
//! of a maximal order O ⊂ B_{p,∞} and separable isogenies from E where
//! End(E) ≅ O.
//!
//! The main algorithms are:
//! - [`IdealToIsogeny`][alg313] (Algorithm 3.13): convert an O₀-ideal to an
//!   isogeny and its images on torsion points
//! - [`FixedDegreeIsogeny`][alg315] (Algorithm 3.15): compute an isogeny of
//!   prescribed degree from precomputed data
//! - [`SuitableIdeals`][alg316] (Algorithm 3.16): decompose an ideal into
//!   pieces with coprime odd norms
//!
//! See [§3.2] of the SQIsign specification.
//!
//! [§3.2]: https://sqisign.org/spec/sqisign-20250707.pdf#section.3.2
//! [alg313]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
//! [alg315]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
//! [alg316]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16

pub(crate) mod endomorphism;
pub(crate) mod precomputed;

use endomorphism::ActionMatrix;
use precomputed::ACTION_MATRICES;

use crate::{
    curves::{
        TorsionBasis, TorsionExponent,
        isogeny::{IsogenyDegree, Kernel as CurveKernel},
        montgomery::{Curve, ProjectiveXOnlyPoint},
        scalar::Scalar,
    },
    params::QUAT_REPRES_BOUND_INPUT,
    quaternions::{
        algebra::Element,
        bigint::BigInt,
        ideal::represent_integer,
        lattice::{ExtremalOrder, Lattice, LeftIdeal},
        precomputed::EXTREMAL_ORDERS,
    },
    surfaces,
};

/// A kernel generator decomposed in a torsion basis (P, Q).
///
/// Represents the point [a]P + [b]Q where a, b are scalars. The
/// actual curve point is computed by evaluating the scalars against
/// a specific torsion basis.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct KernelDecomposition {
    /// Coefficient of P.
    pub a: Scalar,
    /// Coefficient of Q.
    pub b: Scalar,
}

/// Extension trait for computing endomorphism action matrices
/// from quaternion elements already expressed in the order basis.
///
/// Given an element with coordinates (c₀, c₁, c₂, c₃) in the order
/// basis, computes M_α = c₀·M₁ + c₁·M₂ + c₂·M₃ + c₃·M₄ (mod 2^f).
///
/// See §3.2.1.1 of the spec.
pub trait DeuringAction {
    /// Compute the action matrix given four order-basis action matrices.
    ///
    /// The element's (a, b, c, d) coordinates are used as coefficients.
    /// The caller must ensure the element is expressed in the order basis,
    /// not the {1, i, j, k} basis.
    fn action_matrix(&self, basis_matrices: &[ActionMatrix; 4], f: TorsionExponent)
    -> ActionMatrix;
}

impl DeuringAction for Element {
    fn action_matrix(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        f: TorsionExponent,
    ) -> ActionMatrix {
        let coords = [
            *self.a.as_bigint(),
            *self.b.as_bigint(),
            *self.c.as_bigint(),
            *self.d.as_bigint(),
        ];
        let mut result = ActionMatrix::ZERO;
        for i in 0..4 {
            result = result.add_scaled_mod(&coords[i], &basis_matrices[i], f.value());
        }
        result
    }
}

/// Extension trait for converting an ideal to a kernel generator
/// via the Deuring correspondence.
///
/// See [Algorithm 3.14] from the spec.
///
/// [Algorithm 3.14]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.14
pub trait IdealKernel {
    /// Compute the kernel decomposition for this ideal of norm 2^e.
    ///
    /// Returns scalars (a, b) such that ker φ_I is generated by
    /// [a·2^{f-e}]P₀ + [b·2^{f-e}]Q₀, where (P₀, Q₀) is the
    /// precomputed torsion basis of E₀[2^f].
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition>;
}

impl IdealKernel for LeftIdeal<4> {
    fn to_kernel(
        &self,
        basis_matrices: &[ActionMatrix; 4],
        e: TorsionExponent,
    ) -> Option<KernelDecomposition> {
        // Step 1: Find α ∈ O₀ such that I = O₀⟨α, 2^e⟩.
        let alpha = self.generator()?;

        // Step 2: Compute M_α mod 2^e.
        let m_alpha = alpha.action_matrix(basis_matrices, e);

        // Step 3: Find [a, b]^T in the right kernel of M_α mod 2^e.
        // For a 2×2 matrix, the kernel is spanned by (-m01, m00)^T.
        let modulus = BigInt::<4>::ONE.shl(e.value());

        // Try first row: kernel direction = (-m01, m00).
        let a_big = BigInt::<4>::from(*m_alpha.entry(0, 1))
            .wrapping_neg()
            .ct_mod(&modulus);
        let b_big = BigInt::<4>::from(*m_alpha.entry(0, 0)).ct_mod(&modulus);

        let (check0, check1) = m_alpha.eval_mod(&a_big, &b_big, e.value());
        if bool::from(check0.is_zero()) && bool::from(check1.is_zero()) {
            return Some(KernelDecomposition {
                a: Scalar::from(a_big),
                b: Scalar::from(b_big),
            });
        }

        // If first row was zero, try second row.
        let a_big = BigInt::<4>::from(*m_alpha.entry(1, 1))
            .wrapping_neg()
            .ct_mod(&modulus);
        let b_big = BigInt::<4>::from(*m_alpha.entry(1, 0)).ct_mod(&modulus);

        let (check0, check1) = m_alpha.eval_mod(&a_big, &b_big, e.value());
        if bool::from(check0.is_zero()) && bool::from(check1.is_zero()) {
            return Some(KernelDecomposition {
                a: Scalar::from(a_big),
                b: Scalar::from(b_big),
            });
        }

        None
    }
}

// KernelToIdeal (Algorithm 3.17) is TorsionBasis::kernel_to_ideal() in
// curves/mod.rs.

/// Compute the even (non-backtracking) response isogeny.
///
/// Given curve E_chl with torsion basis (P, Q), quaternion α,
/// and integers e' (= e'_rsp) and r (= r_rsp), computes the
/// even response isogeny φ^even_rsp : E_chl → E.
///
/// Returns the codomain curve E and the images P', Q' of the
/// basis points.
///
/// Implements [ComputeEvenNonBacktrackingResponse][Alg. 4.6].
///
/// [Alg. 4.6]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.4.6
pub fn compute_even_response(
    _curve: &Curve,
    P: &ProjectiveXOnlyPoint,
    Q: &ProjectiveXOnlyPoint,
    alpha: &Element,
    e_prime: TorsionExponent,
    r_rsp: TorsionExponent,
) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
    let e_prime = e_prime.value();
    let r_rsp = r_rsp.value();

    // Step 1: I = O₀·α + O₀·(2^r)
    let norm = BigInt::<4>::ONE.shl(r_rsp);
    let ideal = LeftIdeal::new(alpha, &norm, EXTREMAL_ORDERS[0].order());

    // Step 2: (s, t) ← IdealToKernel(I)
    let basis_mats = [
        ACTION_MATRICES[0][3], // gen2
        ACTION_MATRICES[0][4], // gen3
        ACTION_MATRICES[0][5], // gen4
        ACTION_MATRICES[0][0], // i (for the kernel computation)
    ];
    let decomp = ideal.to_kernel(&basis_mats, TorsionExponent::try_from(r_rsp).ok()?)?;

    // Step 3: K = [2^(e'+2) · s]P + [2^(e'+2) · t]Q
    let shift = e_prime + 2;
    let s_shifted = Scalar::from_limbs(*decomp.a.as_limbs()).mul_mod2k(
        &Scalar::from_limbs(*BigInt::<4>::ONE.shl(shift).as_limbs()),
        256,
    );
    let t_shifted = Scalar::from_limbs(*decomp.b.as_limbs()).mul_mod2k(
        &Scalar::from_limbs(*BigInt::<4>::ONE.shl(shift).as_limbs()),
        256,
    );

    // Compute K = [s_shifted]P + [t_shifted]Q using the biladder.
    // Need PmQ for the three-point ladder.
    let PmQ = P.projective_difference(Q);
    let basis = TorsionBasis::new(*P, *Q, PmQ);
    // TODO: PmQ from projective_difference may pick wrong branch.
    // In signing, the basis (P, Q, P-Q) should have been propagated
    // from a prior computation, not recomputed here.
    let K = basis.biscalar_mul(
        &s_shifted,
        &t_shifted,
        TorsionExponent::try_from(r_rsp + shift).ok()?,
    );

    // Step 4: E', {P', Q'} ← TwoisogenyChainSmall(K, E, r, {P, Q}, true)
    let (new_curve, images) = CurveKernel::new(K)
        .isogeny_small(TorsionExponent::try_from(r_rsp).ok()?, &[*P, *Q], true)
        .ok()?;

    Some((new_curve, images[0], images[1]))
}

// ---------------------------------------------------------------------------
// CurveWithEndomorphismRing
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// IdealToIsogeny (Algorithm 3.13) + FixedDegreeIsogeny (Algorithm 3.15)
// ---------------------------------------------------------------------------

/// Compute the action matrix M_α for an element α on E_t[2^f],
/// given the order's lattice and generator action matrices.
///
/// Decomposes α from {1,i,j,k} into the order's column basis
/// (c₀, c₁, c₂, c₃), then assembles:
///
/// M_α = c₀ · I + c₁ · M_{gen2} + c₂ · M_{gen3} + c₃ · M_{gen4}  (mod 2^f)
fn action_matrix(
    elem: &Element,
    order: &Lattice<4>,
    gen_matrices: &[ActionMatrix; 3],
    f: TorsionExponent,
) -> Option<ActionMatrix> {
    let coords = order.decompose(elem)?;

    let c0_mod = coords[0].ct_mod(&BigInt::<4>::ONE.shl(f.value()));
    let c0_scalar = Scalar::from(c0_mod);
    let mut result = ActionMatrix::new(c0_scalar, Scalar::ZERO, Scalar::ZERO, c0_scalar);

    for k in 0..3 {
        result = result.add_scaled_mod(&coords[k + 1], &gen_matrices[k], f.value());
    }

    Some(result)
}

/// Compute a u-isogeny from E_t via a (2,2)-isogeny chain.
///
/// [FixedDegreeIsogeny][Alg. 3.15] (Algorithm [3.15][Alg. 3.15]):
/// given a positive odd [`IsogenyDegree`] u < 2^{f−2} and the
/// precomputed data for curve E_t, finds an endomorphism θ of E_t
/// with nrd(θ) = u·(2^{e_FDI} − u), then computes a
/// (2^{e_FDI}, 2^{e_FDI})-isogeny on E_t × E_t whose projection
/// gives the u-isogeny φ: E_t → E.
///
/// Returns `(E, φ(P_t), φ(Q_t))`.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls RepresentInteger (variable-time
/// search) and the (2,2)-chain length depends on e_FDI.
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived (u, t) values during signing (Algorithm 4.2 via
/// IdealToIsogeny).
///
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
fn fixed_degree_isogeny(
    order: &'static ExtremalOrder<4>,
    u: &IsogenyDegree,
) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
    let f = TorsionExponent::FULL;
    let p_bits = 251u32; // ⌈log₂(p)⌉ for NIST-I

    // Look up the precomputed curve and torsion basis for this order.
    let t = EXTREMAL_ORDERS.iter().position(|o| o.q() == order.q())?;

    // TODO: Support t > 0 with precomputed torsion bases.
    if t != 0 {
        return None;
    }

    let curve_t = Curve::E0;
    let p_t = ProjectiveXOnlyPoint::from_affine_x(precomputed::torsion_basis::e0_px(), &curve_t);
    let q_t = ProjectiveXOnlyPoint::from_affine_x(precomputed::torsion_basis::e0_qx(), &curve_t);
    let basis_t = TorsionBasis::new(p_t, q_t, p_t.projective_difference(&q_t));
    let gen_matrices = [
        ACTION_MATRICES[t][3],
        ACTION_MATRICES[t][4],
        ACTION_MATRICES[t][5],
    ];

    // Step 1: e_FDI = min(f − 2, ⌈log₂(p)⌉ − ⌈log₂(u)⌉ + QUAT_repres_bound_input)
    let e_fdi = core::cmp::min(
        f.value() - 2,
        p_bits.saturating_sub(u.bit_length()) + QUAT_REPRES_BOUND_INPUT,
    );

    // Step 2: θ ← RepresentInteger(u·(2^{e_FDI} − u), O_t, true)
    let u_wide = u.to_bigint_wide();
    let two_e_fdi = BigInt::<8>::ONE.shl(e_fdi);
    let m = u_wide.ct_mul(&two_e_fdi.ct_sub(&u_wide));
    let order_wide = ExtremalOrder::<8>::from(*order);
    let theta = represent_integer(&m, &order_wide, true)?;

    // Step 3: M_θ via order-basis decomposition.
    let m_theta = action_matrix(&theta, order.order(), &gen_matrices, f)?;

    // Step 4–5: Build kernel points on E_t × E_t.
    //
    // θ(P_t) = [m00]P_t + [m10]Q_t  (column 0 of M_θ)
    // θ(Q_t) = [m01]P_t + [m11]Q_t  (column 1 of M_θ)
    let theta_p = basis_t.eval_decomposition(
        &Scalar::from_limbs(*m_theta.entry(0, 0).as_limbs()),
        &Scalar::from_limbs(*m_theta.entry(1, 0).as_limbs()),
    );
    let theta_q = basis_t.eval_decomposition(
        &Scalar::from_limbs(*m_theta.entry(0, 1).as_limbs()),
        &Scalar::from_limbs(*m_theta.entry(1, 1).as_limbs()),
    );

    // K₁ = [2^{f−2−e_FDI}]([u]P_t, θ(P_t))
    // K₂ = [2^{f−2−e_FDI}]([u]Q_t, θ(Q_t))
    let u_scalar = u.to_scalar();
    let mut k1_first = &u_scalar * &basis_t.R;
    let mut k1_second = theta_p;
    let mut k2_first = &u_scalar * &basis_t.S;
    let mut k2_second = theta_q;

    for _ in 0..(f.value() - 2 - e_fdi) {
        k1_first = k1_first.double();
        k1_second = k1_second.double();
        k2_first = k2_first.double();
        k2_second = k2_second.double();
    }

    // Step 6: (2,2)-isogeny chain on E_t × E_t.
    let product = surfaces::EllipticProduct::new(curve_t, curve_t);
    let pmq1 = k1_first.projective_difference(&k2_first);
    let pmq2 = k1_second.projective_difference(&k2_second);
    let kernel = surfaces::Kernel::from_montgomery(
        product,
        (k1_first, k1_second),
        (k2_first, k2_second),
        (pmq1, pmq2),
    )
    .expect("kernel lift failed");

    let zero = ProjectiveXOnlyPoint::identity(&curve_t);
    let (codomain, images) = kernel.isogeny(
        TorsionExponent::try_from(e_fdi).ok()?,
        &[(basis_t.R, zero), (basis_t.S, zero)],
    );

    // Per the spec remark after Algorithm 3.15: when using
    // Isogeny22ChainWithTorsion (Algorithm 8.47), E is always
    // the correct curve and the pairing check can be skipped.
    Some((codomain.E1, images[0].0, images[1].0))
}

/// [IdealToIsogeny][Alg. 3.13] (Algorithm [3.13][Alg. 3.13]).
///
/// Given a left O₀-ideal I, computes the codomain E_I of the
/// corresponding isogeny φ_I : E₀ → E_I, and the images
/// φ_I(P₀) and φ_I(Q₀) of the torsion basis.
///
/// Internally decomposes I via [SuitableIdeals][Alg. 3.16],
/// computes two odd-degree isogenies via [FixedDegreeIsogeny][Alg. 3.15],
/// and combines them through a (2,2)-isogeny chain.
///
/// # Side-channel considerations
///
/// WARNING: Not constant-time — calls SuitableIdeals and
/// RepresentInteger (both variable-time).
///
/// TODO(ct): Make constant-time before production use. Called on
/// secret-derived ideals during signing (Algorithm 4.2).
///
/// [Alg. 3.13]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.13
/// [Alg. 3.15]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.15
/// [Alg. 3.16]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.16
impl LeftIdeal<4> {
    pub fn to_isogeny(self) -> Option<(Curve, ProjectiveXOnlyPoint, ProjectiveXOnlyPoint)> {
        let f = TorsionExponent::FULL;

        // Step 1: Decompose via SuitableIdeals.
        let sui = self.suitable_ideals()?;

        // Steps 2–3: degrees (already in sui.factor1.degree, sui.factor2.degree).
        let d1 = &sui.factor1.degree;
        let _d2 = &sui.factor2.degree;

        // Step 4: E_u, φ_u(P_s), φ_u(Q_s) ← FixedDegreeIsogeny(s, u)
        let u_deg = IsogenyDegree::new_odd(*sui.u.as_limbs())?;
        let (e_u, phi_u_p, phi_u_q) = fixed_degree_isogeny(sui.factor1.order, &u_deg)?;

        // Step 5: E_v, φ_v(P_t), φ_v(Q_t) ← FixedDegreeIsogeny(t, v)
        let v_deg = IsogenyDegree::new_odd(*sui.v.as_limbs())?;
        let (e_v, phi_v_p, phi_v_q) = fixed_degree_isogeny(sui.factor2.order, &v_deg)?;

        // Step 6: [P, Q]^T ← (1/(nrd(I)·nrd(J_t))) M_{β₂} [φ_v(P_t), φ_v(Q_t)]^T
        //
        // For t=0, nrd(J_0) = 1, so the scalar is 1/nrd(I) mod 2^f.
        // TODO: For t > 0, multiply by 1/nrd(J_t) as well.
        let modulus = BigInt::<4>::ONE.shl(f.value());
        let norm_inv = self.norm().invert_mod(&modulus)?;

        // Look up generator action matrices for order O_t.
        let t_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor2.order.q())?;
        let gen_matrices_t = [
            ACTION_MATRICES[t_index][3],
            ACTION_MATRICES[t_index][4],
            ACTION_MATRICES[t_index][5],
        ];
        let m_beta2 = action_matrix(
            &sui.factor2.beta,
            sui.factor2.order.order(),
            &gen_matrices_t,
            f,
        )?;
        let (p_step6, q_step6) = m_beta2.apply_scaled(&norm_inv, phi_v_p, phi_v_q, f);

        // Steps 7–8: Build kernel points on E_u × E_v.
        //
        // K_P ← [2^{f-e}]([d₁]φ_u(P_s), P)
        // K_Q ← [2^{f-e}]([d₁]φ_u(Q_s), Q)
        let d1_scalar = d1.to_scalar();
        let mut kp_first = &d1_scalar * &phi_u_p;
        let mut kq_first = &d1_scalar * &phi_u_q;
        let mut kp_second = p_step6;
        let mut kq_second = q_step6;

        let scale = f.value() - sui.e.value();
        for _ in 0..scale {
            kp_first = kp_first.double();
            kp_second = kp_second.double();
            kq_first = kq_first.double();
            kq_second = kq_second.double();
        }

        // Step 9: (2,2)-isogeny chain.
        let product = surfaces::EllipticProduct::new(e_u, e_v);
        let pmq1 = kp_first.projective_difference(&kq_first);
        let pmq2 = kp_second.projective_difference(&kq_second);
        let kernel = surfaces::Kernel::from_montgomery(
            product,
            (kp_first, kp_second),
            (kq_first, kq_second),
            (pmq1, pmq2),
        )
        .expect("kernel lift failed");

        let zero_v = ProjectiveXOnlyPoint::identity(&e_v);
        let (codomain, images) = kernel.isogeny(sui.e, &[(phi_u_p, zero_v), (phi_u_q, zero_v)]);

        // Steps 10–13: Pick correct output curve.
        // Per Algorithm 8.47 remark, E is always correct when using
        // Isogeny22ChainWithTorsion. Skip pairing check.
        let e_i = codomain.E1;
        let (p_chain, q_chain) = (images[0].0, images[1].0);

        // Step 14: [P_I, Q_I]^T ← (1/(u·d₁)) M_{β₁} [P_I, Q_I]^T
        let s_index = EXTREMAL_ORDERS
            .iter()
            .position(|o| o.q() == sui.factor1.order.q())?;
        let gen_matrices_s = [
            ACTION_MATRICES[s_index][3],
            ACTION_MATRICES[s_index][4],
            ACTION_MATRICES[s_index][5],
        ];
        let m_beta1 = action_matrix(
            &sui.factor1.beta,
            sui.factor1.order.order(),
            &gen_matrices_s,
            f,
        )?;

        // scalar = 1/(u · d₁) mod 2^f
        let ud1 = sui
            .u
            .ct_mul(&BigInt::<4>::from_sign_and_limbs(0, *d1.limbs()));
        let ud1_inv = ud1.invert_mod(&modulus)?;

        let (p_i, q_i) = m_beta1.apply_scaled(&ud1_inv, p_chain, q_chain, f);

        Some((e_i, p_i, q_i))
    }
}

// TODO: Complete KernelDecomposedToIdeal (Algorithm 3.17, partially
// implemented above as kernel_to_ideal).

#[cfg(test)]
mod tests;
