//! Isogeny maps between elliptic curves over finite fields.

use std::{collections::hash_map::HashMap, ops::*};

use crate::{curve::*, field::*, *};

// /// Produces a group which uniquely defines a morphism.
// pub trait Kernel<F>
// where
//     F: FiniteField,
// {
//     /// Get the order of this kernel.
//     // PASS IT IN AND CHECK, DON'T CALC ON USER BEHALF
//     fn order(self: &Self) -> F;
// }

/// An isogeny `φ: E₁ → E₂` between two elliptic curves `E₁` and `E₂`.
///
/// A morphism of curves that sends the origin and kernel elements of `E₁` to
/// the origin of `E₂`.
pub struct Isogeny<P, C, F, K>
where
    P: Point<C, F>,
    C: Curve,
    F: FiniteField,
{
    /// The subset of the domain curve that uniquely defines the isogeny map
    /// from `C` to its codomain curve, as generated by `<P>`.
    kernel: P,

    /// The degree of this isogeny.
    degree: F,

    /// The starting curve.
    domain: C,

    /// The destination curve.
    codomain: C,
}

impl<P, C, F> Isogeny<P, C, F>
where
    P: Point<C, F>,
    C: Curve,
    F: FiniteField,
{
    /// Obtain the individual factors of the composite map.
    pub fn factors(&self) -> HashMap<u64, Isogeny<P, C, F>> {}

    /// Get the degree of the isogeny map.
    pub fn degree(&self) -> F {
        self.degree
    }

    /// Get the dual of this isogeny.
    ///
    /// If `self` is an isogeny map from `E₁` to `E₂`, `dual()` gives you the
    /// isogeny map for the same degree from `E₂` to `E₁`. If you compose
    /// these maps together, you get a map from a curve to itself that is
    /// just scalar multiplication by the original isogeny degree.
    pub fn dual(&self) -> Isogeny<P, C, F> {}
}

mod private {

    use super::*;

    impl<P, C, F> FnOnce<(&P,)> for Isogeny<P, C, F>
    where
        P: Point<C, F>,
        C: Curve,
        F: FiniteField,
    {
        type Output = P;

        #[inline(always)]
        extern "rust-call" fn call_once(self, args: (&P,)) -> Self::Output {}
    }

    impl<P, C, F> FnMut<(&P,)> for Isogeny<P, C, F>
    where
        P: Point<C, F>,
        C: Curve,
        F: FiniteField,
    {
        #[inline(always)]
        extern "rust-call" fn call_mut(&mut self, args: (&P,)) -> Self::Output {}
    }
}

impl<P, C, F> Fn<(&P,)> for Isogeny<P, C, F>
where
    P: Point<C, F>,
    C: Curve,
    F: FiniteField,
{
    #[inline(always)]
    extern "rust-call" fn call(&self, args: (&P,)) -> Self::Output {}
}
