//! NIST-I parameter set constants for SQIsign v3.0 (p324.3).
//!
//! All scheme parameters derive from the prime p = 3 · 2^324 − 1 and the
//! security parameter λ = 128. See [§5.2] (parameter sets) and [§4.7]
//! (precomputed values).
//!
//! [§4.7]: https://sqisign.org/spec/sqisign-20260901.pdf#sec:precomputedValues
//! [§5.2]: https://sqisign.org/spec/sqisign-20260901.pdf#sec:param_sets

pub use crate::fields::fp::FP_ENCODED_BYTES;
use crate::{
    fields::{fp::Fp, fp2::Fp2},
    quaternions::bigint::BigInt,
};

/// The 2-valuation f of p + 1: the largest integer such that 2^f divides p + 1.
///
/// This is the exponent of the full even torsion subgroup E[2^f].
/// f = 324 for NIST-I.
pub const TORSION_EVEN_POWER: u32 = 324;

/// Number of bytes to encode an element of F_{p²}.
pub const FP2_ENCODED_BYTES: usize = 2 * FP_ENCODED_BYTES;

/// Number of bytes to encode a Montgomery curve coefficient A ∈ F_{p²}.
pub const CURVE_ENCODED_BYTES: usize = FP2_ENCODED_BYTES;

/// Verifying key size in bytes: 1 + 2 · 41 ([Table 11]).
///
/// [Table 11]: https://sqisign.org/spec/sqisign-20260901.pdf#tab:byte-sizes
pub const VERIFYING_KEY_BYTES: usize = 1 + 2 * FP_ENCODED_BYTES;

/// Signing key size in bytes: 83 + 3 · 41 + 4 · 16 ([Table 11]).
///
/// [Table 11]: https://sqisign.org/spec/sqisign-20260901.pdf#tab:byte-sizes
pub const SIGNING_KEY_BYTES: usize = VERIFYING_KEY_BYTES + 3 * FP_ENCODED_BYTES + 4 * 16;

/// Signature size in bytes: 2 + 2 · 41 + 4 · 25 + 16 ([Table 11]).
///
/// [Table 11]: https://sqisign.org/spec/sqisign-20260901.pdf#tab:byte-sizes
pub const SIGNATURE_BYTES: usize = 2 + 2 * FP_ENCODED_BYTES + 4 * 25 + 16;

/// Sampling bound for `LeftIdeal::reduce_to_prime_norm` (Algorithm 3.9).
///
/// Random coefficients are sampled from \[−bound, bound\]⁴. Matches
/// the C reference's `QUAT_equiv_bound_coeff` (`precomp/ref/lvl1/
/// include/quaternion_constants.h:4`, value `64`). Must match the C
/// ref byte-for-byte: a smaller bound changes the per-iteration
/// rejection rate AND the integer values produced from a given DRBG
/// byte stream, which desyncs every downstream sample and produces
/// a different reduced ideal — and therefore a different `e_pk` —
/// from the same KAT seed.
pub const EQUIV_BOUND_COEFF: u32 = 64;

/// Number of Miller-Rabin rounds for primality testing in ideal
/// reduction (Algorithm 3.9). Matches the C reference's
/// `QUAT_primality_num_iter` (= 32).
pub const PRIMALITY_NUM_ITER: u32 = 32;

/// Precomputed prime cofactor for [`RandomIdealGivenNorm`][Alg. 3.10]
/// (non-prime case).
///
/// The smallest prime of the same bit size as p, used as the
/// multiplier m in `GeneralizedRepresentInteger(mN, ...)`.
/// For NIST-I: `QUAT_prime_cofactor = 2^251 + 65`.
///
/// [Alg. 3.10]: https://sqisign.org/spec/sqisign-20250707.pdf#algorithm.3.10
pub const QUAT_PRIME_COFACTOR: BigInt<4> = BigInt::from_limbs([0x41, 0, 0, 0x0800_0000_0000_0000]);

/// Commitment/secret isogeny degree D_mix (= `COM_DEGREE` in the C ref).
///
/// The smallest prime > 2^{4λ} = 2^{512}. For NIST-I: `D_mix = 2^512 + 75`.
/// This is 513 bits, so it requires `BigInt<9>` (576 bits). Our ideal
/// infrastructure uses `BigInt<4>` and `BigInt<8>`, so `random_prime_norm`
/// needs to be widened to accept larger norms for the commitment ideal.
///
/// See [§4.2.1] of the spec.
///
/// [§4.2.1]: https://sqisign.org/spec/sqisign-20250707.pdf#subsection.4.2.1
pub const D_MIX: BigInt<9> = BigInt::from_limbs([0x4B, 0, 0, 0, 0, 0, 0, 0, 1]);

/// x-coordinate of the first basis point P₀ of E₀\[2^f\],
/// where f = [`TORSION_EVEN_POWER`].
///
/// (P₀, Q₀) generates E₀\[2^f\] on E₀ : y² = x³ + x, with
/// \[2^(f−1)\]Q₀ = (0, 0). Generated by [Alg. B.1]; value from [§4.7].
/// Stored in Montgomery form, radix-55 representation.
///
/// [Alg. B.1]: https://sqisign.org/spec/sqisign-20260901.pdf#alg:generateBasisE0
/// [§4.7]: https://sqisign.org/spec/sqisign-20260901.pdf#sec:precomputedValues
pub const BASIS_E0_P_X: Fp2 = Fp2::new(
    Fp::from_limbs([
        0x4D1F941FA5BC55,
        0x479E94BE28DDCE,
        0x6954B0F345B16E,
        0x5AD9442DF5213A,
        0x638D3E66829477,
        0x003EE1CC2032A2,
    ]),
    Fp::from_limbs([
        0x76209C4F8803E3,
        0x4C784298DEE866,
        0x1B9F6817AAB089,
        0x06CFA26F0A86B5,
        0x36483D17DF86EA,
        0x018589CDC6E5A6,
    ]),
);

/// x-coordinate of the second basis point Q₀ of E₀\[2^f\],
/// where f = [`TORSION_EVEN_POWER`]. See [`BASIS_E0_P_X`].
pub const BASIS_E0_Q_X: Fp2 = Fp2::new(
    Fp::from_limbs([
        0x1831F97884B24A,
        0x2AEFE1FD831438,
        0x6E182E11818AAD,
        0x081B20586959A1,
        0x3860C88E9247EA,
        0x03FDBD3E81C714,
    ]),
    Fp::from_limbs([
        0x0921CC5CEF3A4D,
        0x465B06C312A1FD,
        0x01041FE4304607,
        0x05C2C7F4AC348E,
        0x18FECA837F8631,
        0x01057A1250E6AA,
    ]),
);

/// x-coordinate of P₀ − Q₀ on E₀, the third component of the
/// canonical basis triple (P₀, Q₀, P₀ − Q₀). See [`BASIS_E0_P_X`].
pub const BASIS_E0_PMQ_X: Fp2 = Fp2::new(
    Fp::from_limbs([
        0x21F10D50FD6891,
        0x5776849C6C523F,
        0x196BE3257223CE,
        0x00E657AB3FF69C,
        0x0A0955076E6C51,
        0x02F694DBC0A375,
    ]),
    Fp::from_limbs([
        0x14FB253F4DADEE,
        0x55C799D249E62E,
        0x0551775BC2283E,
        0x35F68DC8F15703,
        0x37C60333B4C614,
        0x0349A927D578F0,
    ]),
);

#[cfg(test)]
mod tests {
    use super::*;

    /// Checks that x³ + x is a square in F_{p²} (i.e., (x, ·) is on E₀).
    fn is_on_e0(x: &Fp2) -> bool {
        let x2 = x.square();
        let rhs = &(&x2 + &Fp2::ONE) * x;
        bool::from(rhs.is_square())
    }

    #[test]
    fn basis_e0_points_are_on_curve() {
        assert!(is_on_e0(&BASIS_E0_P_X), "P₀ x-coordinate is not on E₀");
        assert!(is_on_e0(&BASIS_E0_Q_X), "Q₀ x-coordinate is not on E₀");
        assert!(
            is_on_e0(&BASIS_E0_PMQ_X),
            "P₀ − Q₀ x-coordinate is not on E₀"
        );
    }

    #[test]
    fn basis_e0_points_are_distinct() {
        assert_ne!(BASIS_E0_P_X, BASIS_E0_Q_X);
        assert_ne!(BASIS_E0_P_X, BASIS_E0_PMQ_X);
        assert_ne!(BASIS_E0_Q_X, BASIS_E0_PMQ_X);
    }

    #[test]
    fn encoded_sizes_match_table_11() {
        assert_eq!(FP_ENCODED_BYTES, 41);
        assert_eq!(VERIFYING_KEY_BYTES, 83);
        assert_eq!(SIGNING_KEY_BYTES, 270);
        assert_eq!(SIGNATURE_BYTES, 200);
    }
}
