#!/usr/bin/env python3
"""Generate the full `torsion_basis` module body for
`src/deuring/precomputed.rs`, with 27 `pub(crate) const Fp2` items in
radix-51 Montgomery form (matching the `BASIS_E0_*` style in
`src/params.rs`).

Reads `torsion_bases.json` (plain-integer x-coordinates of (P_t, Q_t,
P_t - Q_t) on each of the 7 extremal-order curves, plus the curve
coefficient A).

Usage:
    python3 gen_torsion_consts.py > /tmp/module.rs

Cross-check: curve 0's P_X/Q_X/PMQ_X limbs must equal the
`BASIS_E0_P_X`, `BASIS_E0_Q_X`, `BASIS_E0_PMQ_X` constants in
`src/params.rs` (both `(v * R) mod p` with R = 2^255, in canonical
form — any lingering non-canonical form in params.rs is a residue of
the `from_bytes → to_montgomery` path and not a disagreement about
the underlying field element).
"""

import json
import os

p = 5 * 2**248 - 1
R = 2**255
MASK = (1 << 51) - 1

HERE = os.path.dirname(os.path.abspath(__file__))
JSON_PATH = os.path.join(HERE, "torsion_bases.json")


def to_mont_limbs(v_hex: str) -> list[int]:
    """Convert a plain-integer hex string to 5 radix-51 Montgomery limbs."""
    v = int(v_hex, 16) % p
    m = (v * R) % p
    return [(m >> (51 * i)) & MASK for i in range(5)]


def emit_fp2(name: str, doc: str, re_limbs: list[int], im_limbs: list[int]) -> str:
    def body(limbs):
        return (
            "Fp::from_limbs([\n"
            + "".join(f"            0x{limb:013X},\n" for limb in limbs)
            + "        ])"
        )
    return (
        f"    /// {doc}\n"
        f"    pub(crate) const {name}: Fp2 = Fp2::new(\n"
        f"        {body(re_limbs)},\n"
        f"        {body(im_limbs)},\n"
        f"    );"
    )


# NOTE: this script only generates the 27 per-curve `EN_*` constants
# below. The surrounding module header (doc comments, imports) and the
# hand-written `ExtremalCurve` enum, `InvalidCurveIndex`, `TryFrom`,
# and CT `basis()` / `gen_matrices()` methods live in
# `src/deuring/precomputed.rs` and must be edited there directly.
# Running this script emits only the constant block — callers are
# expected to splice it into the existing module body.

HEADER = "// Generated by scripts/precomp/gen_torsion_consts.py — do not edit by hand.\n"
FOOTER = ""


def main():
    with open(JSON_PATH) as f:
        d = json.load(f)

    out = [HEADER]
    for i, c in enumerate(d["curves"]):
        header = (
            f"    // ---- Curve {i} (E₀: y² = x³ + x, A = 0) ----"
            if i == 0
            else f"    // ---- Curve {i} ----"
        )
        out.append("")
        out.append(header)
        out.append("")
        out.append(
            emit_fp2(
                f"E{i}_P_X",
                f"P_{i} x-coordinate.",
                to_mont_limbs(c["P_x_re"]),
                to_mont_limbs(c["P_x_im"]),
            )
        )
        out.append("")
        out.append(
            emit_fp2(
                f"E{i}_Q_X",
                f"Q_{i} x-coordinate.",
                to_mont_limbs(c["Q_x_re"]),
                to_mont_limbs(c["Q_x_im"]),
            )
        )
        out.append("")
        out.append(
            emit_fp2(
                f"E{i}_PMQ_X",
                f"P_{i} − Q_{i} x-coordinate (for consistent Okeya-Sakurai lift).",
                to_mont_limbs(c["PmQ_x_re"]),
                to_mont_limbs(c["PmQ_x_im"]),
            )
        )
        if i != 0:
            out.append("")
            out.append(
                emit_fp2(
                    f"E{i}_A",
                    f"Montgomery coefficient A for curve {i}.",
                    to_mont_limbs(c["A_re"]),
                    to_mont_limbs(c["A_im"]),
                )
            )

    out.append(FOOTER)
    print("\n".join(out))


if __name__ == "__main__":
    main()
