#!/usr/bin/env sage
# Compute p-extremal maximal orders for SQIsign.
#
# Adapted from the SQIsign reference implementation:
# https://github.com/SQISign/the-sqisign
#
# Original authors: the SQIsign team (Maria Corte-Real Santos, Joy Hall,
# Michael Meyer, Giacomo Pope, Damien Robert, et al.)
# Licensed under the Apache License, Version 2.0.
#
# Underlying theory:
# - Ibukiyama, "On maximal orders of division quaternion algebras
#   with certain optimal embeddings"
# - https://ia.cr/2023/106 Lemma 10

from sage.all import *

from sage.misc.banner import require_version
if not require_version(10, 5, print_message=True):
    exit('')

from parameters import p, num_orders as num

################################################################

from sage.algebras.quatalg.quaternion_algebra import basis_for_quaternion_lattice
bfql = lambda els: basis_for_quaternion_lattice(els, reverse=True)

Quat1, (i,j,k) = QuaternionAlgebra(-1, -p).objgens()
assert Quat1.discriminant() == p         # ramifies correctly

O0mat = matrix([list(g) for g in [Quat1(1), i, (i+j)/2, (1+k)/2]])
O0 = Quat1.quaternion_order(list(O0mat))

orders = [ (1, identity_matrix(QQ,4), O0mat, i, O0mat, vector((1,0,0,0))) ]

q = ZZ(1)
while len(orders) < num:
    q = next_prime(q)
    if q % 4 != 1:  # restricting to q = 1 (mod 4)
        continue

    Quatq, (ii,jj,kk) = QuaternionAlgebra(-q, -p).objgens()
    if Quatq.discriminant() != p:       # ramifies incorrectly
        continue

    x, y = QuadraticForm(QQ, 2, [1,0,p]).solve(q)
    gamma = x + j*y
    assert gamma.reduced_norm() == q
    ims1 = [Quat1(1), i*gamma, j, k*gamma]
    assert ims1[1]**2 == -q
    assert ims1[2]**2 == -p
    assert ims1[1]*ims1[2] == ims1[3]
    assert ims1[2]*ims1[1] == -ims1[3]
    # (1,ii,jj,kk)->ims1 is an isomorphism Quatq->Quat1
    iso1q = ~matrix(map(list, ims1))

    r = min(map(ZZ, Mod(-p, 4*q).sqrt(all=True)))

    basq = [
            Quatq(1),
            ii,
            (1 + jj) / 2,
            (r + jj) * ii / 2 / q,
        ]

    Oq = Quatq.quaternion_order(basq)
    assert Oq.discriminant() == p   # is maximal

    mat1 = matrix(map(list, basq)) * ~iso1q
    O1 = Quat1.quaternion_order(list(mat1))
    assert O1.discriminant() == p   # is maximal
    assert j in O1                  # p-extremal

    # look for an odd connecting ideal
    I = O0 * O1
    I *= I.norm().denominator()
    assert I.is_integral()
    for v in IntegralLattice(I.gram_matrix()).enumerate_short_vectors():
        elt = sum(c*g for c,g in zip(v,I.basis()))
        if ZZ(elt.reduced_norm() / I.norm()) % 2:
            break
    I = I * (elt.conjugate() / I.norm())
    assert I.is_integral()
    assert I.norm() % 2
    assert I.left_order() == O0

    O1_ = I.right_order()
    assert O1_.unit_ideal() == elt * O1 * ~elt
    idl1 = matrix(map(list, I.basis()))

    orders.append((q, iso1q, mat1, ims1[1], idl1, vector(elt)))

################################################################
# Output as Rust constants for src/quaternion/precomputed.rs

def to_limbs(val):
    """Convert an integer to four u64 limbs (little-endian)."""
    sign = 0
    if val < 0:
        sign = 1
        val = -val
    limbs = []
    for _ in range(4):
        limbs.append(val & 0xffffffffffffffff)
        val >>= 64
    assert val == 0, f"value too large for four limbs: {hex(val)}"
    return sign, limbs

def fmt_bigint(val):
    sign, limbs = to_limbs(ZZ(val))
    ls = ', '.join(f'0x{l:016x}' for l in limbs)
    return f'BigInt::from_sign_and_limbs({sign}, [{ls}])'

def fmt_zero():
    return 'BigInt::ZERO'

def fmt_one():
    return 'BigInt::ONE'

def fmt_bigint_smart(val):
    val = ZZ(val)
    if val == 0:
        return fmt_zero()
    if val == 1:
        return fmt_one()
    if val == -1:
        return 'BigInt::MINUS_ONE'
    return fmt_bigint(val)

print("// Auto-generated by scripts/precomp/maxorders.py")
print("// Do not edit manually.")
print()
print(f"// p = {hex(p)}")
print()

for idx, (q, iso1q, mat1, z_elt, idl1, conj_elt) in enumerate(orders):
    # Extract basis matrix (row-major, 4x4)
    basis = mat1
    # Find a common denominator for the basis
    denoms = [entry.denominator() for row in basis for entry in row]
    denom = lcm(denoms)
    int_basis = matrix(ZZ, [[ZZ(entry * denom) for entry in row] for row in basis])

    # z element
    z_coords = list(z_elt)
    z_denoms = [c.denominator() for c in z_coords]
    z_denom = lcm(z_denoms)
    z_int = [ZZ(c * z_denom) for c in z_coords]

    print(f'// Order {idx} (q = {q})')
    print(f'// basis denom = {denom}')
    print(f'// z denom = {z_denom}')
    print(f'// z coords = {z_int}')
    print(f'// basis:')
    for row in range(4):
        vals = [int_basis[row][col] for col in range(4)]
        print(f'//   row {row}: {vals}')
    print()

print("q values:", [q for q, *_ in orders])
